name: 'Start SEED'
description: 'Starts SEED server and services using Docker compose'
runs:
  using: "composite"
  steps: 
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: debug-${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          debug-${{ runner.os }}-buildx-
    -
      name: Build Docker dev image
      run: /usr/bin/docker buildx build --tag seedplatform/seed:dev --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache,mode=max --load --file Dockerfile-dev .
    -
      name: Start the stack
      run: |
        docker volume create --name=seed_pgdata
        docker volume create --name=seed_media
        docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
    -
      name: Setup SEED
      run: |
        docker exec seed_web_1 ./manage.py migrate
        docker exec seed_web_1 ./manage.py create_default_user --username=demo@example.com --password=demo123
        docker exec seed_web_1 /bin/bash -c 'echo "y" | ./manage.py make_superuser --user demo@example.com'
