# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20171120_1158'),
        ('orgs', '0004_auto_20180106_2123'),
    ]

    operations = [
    ]
