# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_merge_20180110_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_significant_figures',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
