# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20170819_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='measurement_system_display',
            field=models.IntegerField(choices=[(1, b'IP units - kBtu/ft\xc2\xb2/year'), (2, b'SI units - GJ/m\xc2\xb2/year'), (3, b'SI units - kWh/m\xc2\xb2/year')], default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='measurement_system_import',
            field=models.IntegerField(choices=[(1, b'IP units - kBtu/ft\xc2\xb2/year'), (2, b'SI units - GJ/m\xc2\xb2/year'), (3, b'SI units - kWh/m\xc2\xb2/year')], default=1),
        ),
    ]
