# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_organization_mapquest_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_meter_units',
            field=models.JSONField(default={'Coal (anthracite)': 'kBtu', 'Coal (bituminous)': 'kBtu', 'Coke': 'kBtu', 'Diesel': 'kBtu', 'District Chilled Water': 'kBtu', 'District Hot Water': 'kBtu', 'District Steam': 'kBtu', 'Electricity': 'kBtu', 'Fuel Oil (No. 1)': 'kBtu', 'Fuel Oil (No. 2)': 'kBtu', 'Fuel Oil (No. 4)': 'kBtu', 'Fuel Oil (No. 5 & No. 6)': 'kBtu', 'Kerosene': 'kBtu', 'Natural Gas': 'kBtu', 'Other': 'kBtu', 'Propane': 'kBtu', 'Wood': 'kBtu'}),
        ),
        migrations.AddField(
            model_name='organization',
            name='thermal_conversion_assumption',
            field=models.IntegerField(choices=[(1, 'US'), (2, 'CAN')], default=1),
        ),
    ]
