# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 19:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def update_display_meter_units_options(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    default_display_options = {
        'Coal (anthracite)': 'kBtu',
        'Coal (bituminous)': 'kBtu',
        'Coke': 'kBtu',
        'Diesel': 'kBtu',
        'District Chilled Water - Absorption': 'kBtu',
        'District Chilled Water - Electric': 'kBtu',
        'District Chilled Water - Engine': 'kBtu',
        'District Chilled Water - Other': 'kBtu',
        'District Hot Water': 'kBtu',
        'District Steam': 'kBtu',
        'Electric - Grid': 'kBtu',
        'Electric - Solar': 'kBtu',
        'Electric - Wind': 'kBtu',
        'Fuel Oil (No. 1)': 'kBtu',
        'Fuel Oil (No. 2)': 'kBtu',
        'Fuel Oil (No. 4)': 'kBtu',
        'Fuel Oil (No. 5 and No. 6)': 'kBtu',
        'Kerosene': 'kBtu',
        'Natural Gas': 'kBtu',
        'Other:': 'kBtu',
        'Propane': 'kBtu',
        'Wood': 'kBtu'
    }
    Organization.objects.all().update(display_meter_units=default_display_options)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_organization_meter_related_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='display_meter_units',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Coal (anthracite)': 'kBtu', 'Coal (bituminous)': 'kBtu', 'Coke': 'kBtu', 'Diesel': 'kBtu', 'District Chilled Water - Absorption': 'kBtu', 'District Chilled Water - Electric': 'kBtu', 'District Chilled Water - Engine': 'kBtu', 'District Chilled Water - Other': 'kBtu', 'District Hot Water': 'kBtu', 'District Steam': 'kBtu', 'Electric - Grid': 'kBtu', 'Electric - Solar': 'kBtu', 'Electric - Wind': 'kBtu', 'Fuel Oil (No. 1)': 'kBtu', 'Fuel Oil (No. 2)': 'kBtu', 'Fuel Oil (No. 4)': 'kBtu', 'Fuel Oil (No. 5 and No. 6)': 'kBtu', 'Kerosene': 'kBtu', 'Natural Gas': 'kBtu', 'Other:': 'kBtu', 'Propane': 'kBtu', 'Wood': 'kBtu'}),
        ),
    ]
