# Generated by Django 2.2.10 on 2020-03-27 19:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import seed.lib.superperms.orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20190714_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='display_meter_units',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=seed.lib.superperms.orgs.models._get_default_display_meter_units),
        ),
    ]
