# Generated by Django 2.2.10 on 2020-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20200327_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='comstock_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
