# Generated by Django 2.2.13 on 2020-11-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_organization_comstock_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='geocoding_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
