# Generated by Django 2.2.13 on 2021-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_organization_property_display_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='taxlot_display_field',
            field=models.CharField(default='address_line_1', max_length=32),
        ),
    ]
