# Generated by Django 2.2.13 on 2021-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_organization_taxlot_display_field'),
    ]

    default_content = "Hello {{first_name}},\nYou are receiving this e-mail because you have been registered for a SEED account.\nSEED is easy, flexible, and cost effective software designed to help organizations clean, manage and share information about large portfolios of buildings. SEED is a free, open source web application that you can use privately.  While SEED was originally designed to help cities and States implement benchmarking programs for public or private buildings, it has the potential to be useful for many other activities by public entities, efficiency programs and private companies.\nPlease go to the following page and setup your account:\n{{sign_up_link}}"
    default_email = "info@seed-platform.org"
    default_signature = "The SEED Team"
    default_subject = "New SEED account"

    operations = [
        migrations.AddField(
            model_name='organization',
            name='new_user_email_content',
            field=models.CharField(default=default_content, max_length=1024),
        ),
        migrations.RunSQL("ALTER TABLE %s ALTER COLUMN new_user_email_content SET DEFAULT '%s';" % ('orgs_organization', default_content)),
        migrations.AddField(
            model_name='organization',
            name='new_user_email_from',
            field=models.CharField(default=default_email, max_length=128),
        ),
        migrations.RunSQL("ALTER TABLE %s ALTER COLUMN new_user_email_from SET DEFAULT '%s';" % ('orgs_organization', default_email)),
        migrations.AddField(
            model_name='organization',
            name='new_user_email_signature',
            field=models.CharField(default=default_signature, max_length=128),
        ),
        migrations.RunSQL("ALTER TABLE %s ALTER COLUMN new_user_email_signature SET DEFAULT '%s';" % ('orgs_organization', default_signature)),
        migrations.AddField(
            model_name='organization',
            name='new_user_email_subject',
            field=models.CharField(default=default_subject, max_length=128),
        ),
        migrations.RunSQL("ALTER TABLE %s ALTER COLUMN new_user_email_subject SET DEFAULT '%s';" % ('orgs_organization', default_subject)),
    ]
