# Generated by Django 2.2.24 on 2021-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_update_organization_display_meter_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='better_analysis_api_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
