# Generated by Django 3.2.7 on 2021-10-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_organization_better_analysis_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='display_significant_figures',
            new_name='display_decimal_places',
        ),
    ]
