# Generated by Django 3.2.16 on 2023-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_auto_20220721_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='salesforce_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
