# Generated by Django 3.2.18 on 2023-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion
from django.db import transaction


@transaction.atomic
def give_org_access_level_root(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    AccessLevelInstance = apps.get_model('orgs', 'AccessLevelInstance')

    orgs = Organization.objects.all()
    for i, org in enumerate(orgs):
        org.access_level_names = [org.name]
        org.save()

        AccessLevelInstance.objects.create(
            tree_id=i,
            organization=org,
            name="root",
            path={org.access_level_names[0]: "root"}, 
            depth=1,
            lft=1,
            rgt=2,
        ).save()


@transaction.atomic
def assign_users_to_root_acces_level(apps, schema_editor):
    OrganizationUser = apps.get_model('orgs', 'OrganizationUser')
    AccessLevelInstance = apps.get_model('orgs', 'AccessLevelInstance')

    users = OrganizationUser.objects.all()
    for user in users:
        user.access_level_instance = user.organization.root
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_salesforce_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access_level_names',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='AccessLevelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('path', models.JSONField(null=False))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(give_org_access_level_root),
        migrations.AddField(
            model_name='organizationuser',
            name='access_level_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.accesslevelinstance', related_name="users"),
        ),
        migrations.RunPython(assign_users_to_root_acces_level, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organizationuser',
            name='access_level_instance',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.accesslevelinstance', related_name="users"),
        )
    ]
