# Generated by Django 3.2.19 on 2023-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_salesforce_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ubid_threshold',
            field=models.FloatField(default=0.0),
        ),
    ]
