# Generated by Django 3.2.19 on 2023-05-24 17:49

from django.db import migrations, models, transaction

@transaction.atomic 
def backfill_ubid_thresholds(apps, schema_editor):
    Organization = apps.get_model("orgs", "Organization")

    organizations = Organization.objects.filter(ubid_threshold__isnull=True).update(ubid_threshold=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_organizationuser_unique_user_for_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ubid_threshold',
            field=models.FloatField(null=True, default=0.0),
        ),
        migrations.RunPython(backfill_ubid_thresholds),
        migrations.AlterField(
            model_name='organization',
            name='ubid_threshold',
            field=models.FloatField(default=0.0),
        ),
    ]
