# Generated by Django 3.2.19 on 2023-05-24 17:49

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0026_organizationuser_unique_user_for_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ubid_threshold',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(('ubid_threshold__range', (0, 1))),
                                              name='ubid_threshold_range'),
        ),
    ]
