# Generated by Django 3.2.19 on 2023-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0026_organizationuser_unique_user_for_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ubid_threshold',
            field=models.FloatField(null=True, default=1.0),
        ),
    ]
