# Generated by Django 3.2.20 on 2023-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_organization_ubid_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_template_report_type',
            field=models.CharField(blank=True, default='Demo City Report', max_length=128),
        ),
    ]
