# Generated by Django 3.2.20 on 2023-08-30 20:25

from django.db import migrations, models, transaction


@transaction.atomic
def backfill_org_audit_template_report_type(apps, schema_editor):
    Organization = apps.get_model("orgs", "Organization")
    for org in Organization.objects.all():
        org.audit_template_report_type = "Demo City Report"
        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0027_organization_ubid_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="audit_template_report_type",
            field=models.CharField(blank=True, default="Demo City Report", max_length=128),
        ),
        migrations.RunPython(backfill_org_audit_template_report_type),
    ]
