# Generated by Django 3.2.23 on 2024-02-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_auto_20240105_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_template_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
