# Generated by Django 3.2.25 on 2024-03-26 14:21

from django.db import migrations


from django.db import migrations, transaction
from seed.utils.encrypt import decrypt, encrypt

@transaction.atomic
def encrypt_existing_audit_template_passwords(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')

    for org in Organization.objects.iterator():
        org.audit_template_password = encrypt(org.audit_template_password)
        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0030_accountability_hierarchy'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_audit_template_passwords),
    ]
