
# Generated by Django 3.2.23 on 2024-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0030_accountability_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_template_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='audit_template_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
