# Generated by Django 3.2.25 on 2024-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0031_encrypt_existing_audit_template_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="require_2fa",
            field=models.BooleanField(default=False),
        ),
    ]
