# Generated by Django 3.2.25 on 2024-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0031_encrypt_existing_audit_template_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="display_units_water_use",
            field=models.CharField(blank=True, choices=[("kgal", "kgal")], default="kgal", max_length=32),
        ),
        migrations.AddField(
            model_name="organization",
            name="display_units_wui",
            field=models.CharField(blank=True, choices=[("kgal/ft**2/year", "kgal/ft**2/year")], default="kgal/ft**2/year", max_length=32),
        ),
    ]
