# Generated by Django 3.2.25 on 2024-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0031_encrypt_existing_audit_template_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_feed_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
