# Generated by Django 3.2.25 on 2024-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0032_organization_public_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_geojson_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
