# Generated by Django 3.2.25 on 2024-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0033_organization_public_geojson_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="require_2fa",
            field=models.BooleanField(default=False),
        ),
    ]
