# Generated by Django 3.2.25 on 2024-07-17 16:56

from django.db import migrations, models

import seed.lib.superperms.orgs.models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0033_organization_public_geojson_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="display_meter_water_units",
            field=models.JSONField(default=seed.lib.superperms.orgs.models._get_default_meter_water_units),
        ),
    ]
