# Generated by Django 3.2.25 on 2024-07-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0036_organization_display_meter_water_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="display_units_water_use",
            field=models.CharField(
                choices=[("kgal/year", "kgal/year"), ("gal/year", "gal/year"), ("L/year", "L/year")], default="kgal/year", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="display_units_wui",
            field=models.CharField(
                choices=[("kgal/ft**2/year", "kgal/ft²/year"), ("gal/ft**2/year", "gal/ft²/year"), ("L/m**2/year", "L/m²/year")],
                default="gal/ft**2/year",
                max_length=32,
            ),
        ),
    ]
