# Generated by Django 3.2.25 on 2024-09-10 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0038_alter_organization_audit_template_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="ubid_threshold",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1.0)]
            ),
        ),
        migrations.RemoveConstraint(
            model_name='organization',
            name='ubid_threshold_range',
        ),
    ]
