# Generated by Django 3.2.25 on 2025-02-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0039_alter_organization_ubid_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="audit_template_export_measures",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="audit_template_export_meters",
            field=models.BooleanField(default=True),
        ),
    ]
