# Generated by Django 3.2.25 on 2025-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0040_add_at_export_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="audit_template_tracking_id_field",
            field=models.CharField(blank=True, default="custom_id_1", max_length=128),
        ),
        migrations.AddField(
            model_name="organization",
            name="audit_template_tracking_id_name",
            field=models.CharField(blank=True, default="City Custom Building ID", max_length=128),
        ),
    ]
