# Generated by Django 3.2.25 on 2025-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0041_add_at_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationuser",
            name="settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
