# Generated by Django 3.2.25 on 2025-10-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0042_organizationuser_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bb_salesforce_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
