# Generated by Django 4.2.24 on 2025-11-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0042_organizationuser_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_template_export_federal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='audit_template_federal_agency',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
