# Generated by Django 4.2.26 on 2026-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0044_add_bb_salesforce_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="max_data_charted",
            field=models.IntegerField(default=3000),
        ),
    ]
