# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

changelog:
  exclude:
    labels:
      - DO NOT MERGE
      - Verify No Longer Relevant
      - No Longer Valid
      - Not Reproducible
      - Duplicate
      - To Investigate
      - Do not publish
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - Feature
    - title: Improvements 📈
      labels:
        - Enhancement
    - title: Maintenance 🧹
      labels:
        - Maintenance
        - Documentation
        - Performance
    - title: Bug Fixes 🐛
      labels:
        - Bug
    - title: Other Changes
      labels:
        - "*"
