FROM node:22-alpine3.19

RUN apk add --no-cache \
        postgresql-dev \
        coreutils \
        alpine-sdk \
        pcre \
        pcre-dev \
        libxslt-dev \
        linux-headers \
        libffi-dev \
        bash \
        bash-completion \
        nginx \
        brotli \
        nginx-mod-http-brotli \
        openssl-dev \
        geos-dev \
        gdal \
        gdal-dev \
        proj-dev \
        proj-util \
        gcc \
        musl-dev \
        cargo \
        tzdata \
        bzip2-dev \
        readline-dev \
        sqlite-dev \
        ncurses-dev \
        xz-dev \
        zlib-dev \
        libxml2-dev \
        hdf5-dev \
        hdf5 \
        netcdf-dev && \
    mkdir -p /var/log/supervisord && \
    mkdir -p /run/nginx

## Note on some of the commands above:
##   - coreutils is required due to an issue with our wait-for-it.sch script:
##     https://github.com/vishnubob/wait-for-it/issues/71

# Install pyenv and Python globally
ENV PYTHON_VERSION=3.9.22
ENV PYENV_ROOT="/opt/pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

RUN git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT && \
    $PYENV_ROOT/bin/pyenv install $PYTHON_VERSION && \
    $PYENV_ROOT/bin/pyenv global $PYTHON_VERSION && \
    ln -sf $PYENV_ROOT/shims/python /usr/local/bin/python && \
    ln -sf $PYENV_ROOT/shims/python3 /usr/local/bin/python3 && \
    ln -sf $PYENV_ROOT/shims/pip /usr/local/bin/pip && \
    ln -sf $PYENV_ROOT/shims/pip3 /usr/local/bin/pip3

# Make sure non-root users inherit pyenv paths
ENV PYENV_ROOT="/opt/pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

# Install pip
RUN bash -c "python3 -m ensurepip --upgrade && python3 -m pip install --upgrade pip setuptools && \
    pip install supervisor==4.2.5"

### Install python requirements
WORKDIR /seed
COPY ./requirements.txt /seed/requirements.txt
COPY ./requirements/*.txt /seed/requirements/
RUN pip uninstall -y enum34
RUN pip install -r requirements/local.txt
# for remote debugging
RUN pip install remote-pdb
# for live reloading celery
RUN pip install watchdog[watchmedo]

### Install JavaScript requirements - do this first because they take awhile
### and the dependencies will probably change slower than python packages.
### README.md stops the no readme warning
COPY ./package.json /seed/package.json
COPY ./package-lock.json /seed/package-lock.json
COPY ./vendors/package.json /seed/vendors/package.json
COPY ./vendors/package-lock.json /seed/vendors/package-lock.json
COPY ./ng_seed/seed-angular/package.json /seed/ng_seed/seed-angular/package.json
COPY ./ng_seed/seed-angular/pnpm-lock.yaml /seed/ng_seed/seed-angular/pnpm-lock.yaml
COPY ./ng_seed/seed-angular/pnpm-workspace.yaml /seed/ng_seed/seed-angular/pnpm-workspace.yaml
COPY ./README.md /seed/README.md
# unsafe-perm allows the package.json postinstall script to run with the elevated permissions
RUN npm install --unsafe-perm

### Copy over the remaining part of the SEED application and some helpers
WORKDIR /seed
COPY . /seed/
COPY ./docker/wait-for-it.sh /usr/local/wait-for-it.sh
RUN git config --system --add safe.directory /seed

### Build SEED Angular
# RUN npm install -g pnpm
# RUN pnpm -C /seed/ng_seed/seed-angular install
# RUN pnpm -C /seed/ng_seed/seed-angular build

EXPOSE 80

CMD ["python", "manage.py", "runserver", "--settings=config.settings.docker_dev", "0.0.0.0:80"]
