sharedWorkspaceLockfile: false

packages:
  - .
  - ng_seed/seed-angular
  - vendors

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  puppeteer: true
  unrs-resolver: true
