# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0018_auto_20160614_1330'),
        ('seed', '0018_auto_20160609_0841'),
    ]

    operations = [
    ]
