# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0004_auto_20160411_1139'),
        ('seed', '0020_auto_20160725_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='import_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_importer.ImportFile'),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='source_type',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
