# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0021_auto_20160727_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='data_state',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Post Import'), (2, 'Post Mapping'), (3, 'Post Matching')], default=0),
        ),
    ]
