# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='confidence',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
