# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20160412_1123'),
        ('seed', '0022_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyauditlog',
            old_name='creation_dat',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='propertyauditlog',
            name='childstate_id',
        ),
        migrations.RemoveField(
            model_name='propertyauditlog',
            name='parentstate_id1',
        ),
        migrations.RemoveField(
            model_name='propertyauditlog',
            name='parentstate_id2',
        ),
        migrations.RemoveField(
            model_name='taxlotauditlog',
            name='childstate_id',
        ),
        migrations.RemoveField(
            model_name='taxlotauditlog',
            name='parentstate_id1',
        ),
        migrations.RemoveField(
            model_name='taxlotauditlog',
            name='parentstate_id2',
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propertyauditlog__child', to='seed.PropertyState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='import_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertyauditlog__parent1', to='seed.PropertyState'),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertyauditlog__parent2', to='seed.PropertyState'),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), ('AUDIT_USER_EDIT', 'UserEdit')], null=True),
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taxlotauditlog__child', to='seed.TaxLotState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='import_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxlotauditlog__parent1', to='seed.TaxLotState'),
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxlotauditlog__parent2', to='seed.TaxLotState'),
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), ('AUDIT_USER_EDIT', 'UserEdit')], null=True),
        ),
    ]
