# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0021_auto_20160818_1016'),
        ('seed', '0023_auto_20160817_0901'),
    ]

    operations = [
    ]
