# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0003_auto_20160602_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='cycle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 7, 18, 58, 15, 871791, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
