# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0005_auto_20160609_1142'),
        ('bluesky', '0003_auto_20160610_0101'),
    ]

    operations = [
    ]
