# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0026_auto_20160822_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyauditlog',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='taxlotauditlog',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='propertyauditlog',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyauditlog__state', to='seed.PropertyState'),
        ),
        migrations.AlterField(
            model_name='taxlotauditlog',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxlotauditlog__state', to='seed.TaxLotState'),
        ),
    ]
