# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0027_auto_20160822_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyauditlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertyauditlog__view', to='seed.PropertyView'),
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxlotauditlog',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxlotauditlog__view', to='seed.TaxLotView'),
        ),
    ]
