# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0024_merge'),
        ('seed', '0028_auto_20160824_1642'),
    ]

    operations = [
    ]
