# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0007_propertystate_pm_parent_property_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together=set([('property', 'cycle')]),
        ),
        migrations.AlterUniqueTogether(
            name='taxlotview',
            unique_together=set([('taxlot', 'cycle')]),
        ),
    ]
