# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0030_column_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyview',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='taxlotview',
            name='labels',
        ),
        migrations.AddField(
            model_name='property',
            name='labels',
            field=models.ManyToManyField(to='seed.StatusLabel'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='labels',
            field=models.ManyToManyField(to='seed.StatusLabel'),
        ),
    ]
