# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0030_column_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Property')),
                ('statuslabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.StatusLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TaxLotLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuslabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.StatusLabel')),
                ('taxlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.TaxLot')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='labels',
            field=models.ManyToManyField(through='seed.PropertyLabels', to='seed.StatusLabel'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='labels',
            field=models.ManyToManyField(through='seed.TaxLotLabels', to='seed.StatusLabel'),
        ),
    ]
