# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0032_auto_20160909_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyview',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='taxlotview',
            name='labels',
        ),
    ]
