# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0032_migrate_label_data'),
        #('seed', '0031_auto_20160912_1155'),
        ('seed', '0031_auto_20160913_0001'),
    ]

    operations = [
    ]
