# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0033_merge'),
        ('seed', '0032_auto_20160916_1212'),
    ]

    operations = [
    ]
