# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0039_auto_20161013_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.PropertyAuditLog'),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.TaxLotAuditLog'),
        ),
    ]
