# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0040_auto_20161014_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), (1, 'UserEdit'), (2, 'MergeState')], null=True),
        ),
        migrations.AlterField(
            model_name='taxlotauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), (1, 'UserEdit'), (2, 'MergeState')], null=True),
        ),
    ]
