# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20160412_1123'),
        ('seed', '0043_auto_20161025_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('recognition_type', models.CharField(choices=[('AWD', 'Award'), ('CRT', 'Certification'), ('LBL', 'Label'), ('PRT', 'Participant'), ('RAT', 'Rating'), ('SCR', 'Score'), ('ZER', 'Zero Energy Ready Home')], default='CRT', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_numeric_score', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GreenAssessmentProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('metric', models.FloatField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('eligibility', models.NullBooleanField()),
                ('_expiration_date', models.DateField(blank=True, null=True)),
                ('extra_data', django_pgjson.fields.JsonField(blank=True, default={})),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.GreenAssessment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.PropertyView')),
            ],
        ),
        migrations.CreateModel(
            name='GreenAssessmentURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('validity_duration', models.DurationField(blank=True, default=None, null=True)),
                ('property_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='seed.GreenAssessmentProperty')),
            ],
        ),
    ]
