# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0043_auto_20161025_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='property_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
