# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0044_propertystate_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='lot_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
