# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0044_greenassessment_greenassessmentproperty_greenassessmenturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenassessmenturl',
            name='validity_duration',
        ),
        migrations.AddField(
            model_name='greenassessment',
            name='validity_duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
