# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 21:18
from __future__ import unicode_literals

from django.db import migrations

from seed.models.columns import Column, ColumnMapping


# from seed.utils.generic import pp

def forwards(apps, schema_editor):
    # find which columns are not used in column mappings
    not_used_count = 0
    double_usage_count = 0

    # return

    for c in Column.objects.all():
        print "Column {}: {}.{}".format(c.id, c.table_name, c.column_name)
        cm_raw = ColumnMapping.objects.filter(column_raw=c)
        cm_mapped = ColumnMapping.objects.filter(column_mapped=c)

        # check if the column isn't used
        if cm_raw.count() == 0 and cm_mapped.count() == 0:
            print "    deleting column: not used in mappings"
            not_used_count += 1
            # c.delete()
            continue

        if cm_raw.count() > 1:
            print "    used in {} 'from' mapping(s)".format(cm_raw.count())
            for c_i in (1, cm_raw.count()-1):
                print "     iterating over ColumnMapping for {}".format(cm_raw[c_i])
                print "     creating a new column for i {}".format(c_i)
            #     new_c = Column.objects.get(pk=c.id)
            #     new_c.pk = None
            #     new_c.save()
            #     cm_raw[c_i].column_raw.clear()
            #     cm_raw[c_i].column_raw.add(new_c)
            #     cm_raw[c_i].save()
            #
            # # save the cm_raw to only include the orginal
            # cm_raw.column_raw.clear()
            # cm_raw.column_raw.add(c)

        if cm_mapped.count() > 1:
            print "    used in {} 'to' mapping(s)".format(cm_mapped.count())
            for cm in cm_mapped:
                print "     iterating over ColumnMapping for {}".format(cm)
                print "     creating a new column"

        if cm_raw.count() >= 1 and cm_mapped.count() >= 1:
            print "    duplicate 'from' and 'to' column used in same mapping(s)"
            double_usage_count += 1

            continue

        # Any cm_raw columns should not have a table_name and not be extra data
        if cm_raw.count() == 1:
            if c.table_name != '':
                print "    raw column table name is not blank, making it ''"
                c.table_name = ''
            if c.is_extra_data:
                print "    raw column is set to extra_data, bad!, unsetting"
                c.is_extra_data = False
            # c.save()

        if cm_mapped.count() == 1:
            if c.table_name == '':
                print "    mapped column has table_name set to '', setting to PropertyState"
                c.table_name = 'PropertyState'
            # c.save()


    print "Total unused columns: {}".format(not_used_count)
    print "Total from/to used duplicate columns: {}".format(double_usage_count)
    print "Total Columns: {}".format(Column.objects.all().count())

    exit()


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0047_auto_20170119_1318'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
