# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0047_auto_20170119_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='merge_state',
            field=models.IntegerField(
                choices=[(0, b'Unknown'), (1, b'New Record'), (2, b'Merged Record'),
                         (3, b'Duplicate Record'), (4, b'Delete Record')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='taxlotstate',
            name='merge_state',
            field=models.IntegerField(
                choices=[(0, b'Unknown'), (1, b'New Record'), (2, b'Merged Record'),
                         (3, b'Duplicate Record'), (4, b'Delete Record')], default=0, null=True),
        ),
    ]
