# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-20 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0052_auto_20170307_0955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set([]),
        ),
    ]
