# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 21:18
from __future__ import unicode_literals

from django.db import migrations

from seed.models.columns import Column, ColumnMapping

def forwards(apps, schema_editor):
    # find which columns are not used in column mappings
    not_used_count = 0

    for c in Column.objects.all():
        cm_raw = ColumnMapping.objects.filter(column_raw=c)
        cm_mapped = ColumnMapping.objects.filter(column_mapped=c)

        # check if the column isn't used
        if cm_raw.count() == 0 and cm_mapped.count() == 0:
            print "Column {}: {}.{}".format(c.id, c.table_name, c.column_name)
            print "    deleting column: not used in any mappings"
            not_used_count += 1
            c.delete()
            continue

    print ""
    print ""
    print "-------------------------------------------------------------------"
    print "Total unused columns: {}".format(not_used_count)
    print "Total Columns: {}".format(Column.objects.all().count())


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0054_remove_same_column_in_mappings'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
