# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0056_cleanup_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='extra_data_source',
        ),
    ]
