# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0002_auto_20170420_1415'),
        ('seed', '0060_column_import_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslabel',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_quality.Rule'),
        ),
    ]
