# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0061_statuslabel_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslabel',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_quality.Rule'),
        ),
    ]
