# Generated by Django 1.9.5 on 2017-05-10 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0061_dataqualitycheck_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="status_label",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="seed.StatusLabel"),
        ),
    ]
