# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0062_auto_20170510_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='text_match',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
