# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 18:55
from __future__ import unicode_literals

from django.db import migrations

# remove the cleansing_rules from the database

DROP_ACCOUNT_TABLES = """\
    DROP TABLE IF EXISTS cleansing_rules CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0063_rule_text_match'),
    ]

    operations = [
        migrations.RunSQL(DROP_ACCOUNT_TABLES),
    ]



