# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0064_auto_20170516_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualitycheck',
            name='name',
            field=models.CharField(default=b'Default Data Quality Check', max_length=255),
        ),
    ]
