# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0066_auto_20170522_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='taxlotstate',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='buildingsnapshot',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='buildingsnapshot',
            name='extra_data_sources',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='custombuildingheaders',
            name='building_headers',
            field=models.JSONField(default=dict),
        ),
    ]
