# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-02 14:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0066_auto_20170522_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='taxlotstate',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
