# Generated by Django 1.9.13 on 2017-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0067_auto_20170602_0740"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="propertystate",
            index=models.Index(fields=["import_file", "data_state"], name="seed_propertystate_import_file_id_data_state_03d5947e_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyview",
            index=models.Index(fields=["state", "cycle"], name="seed_propertyview_state_id_cycle_id_0b1e0dc3_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotproperty",
            index=models.Index(fields=["cycle", "property_view"], name="seed_taxlotproperty_cycle_id_property_view_id_f2589e49_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotproperty",
            index=models.Index(fields=["cycle", "taxlot_view"], name="seed_taxlotproperty_cycle_id_taxlot_view_id_540a3b34_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotproperty",
            index=models.Index(fields=["property_view", "taxlot_view"], name="seed_taxlotproperty_property_view_id_taxlot__5ec224b3_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotstate",
            index=models.Index(fields=["import_file", "data_state"], name="seed_taxlotstate_import_file_id_data_state_1b45dff3_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotview",
            index=models.Index(fields=["state", "cycle"], name="seed_taxlotview_state_id_cycle_id_02b04177_idx"),
        ),
    ]
