# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 16:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0067_auto_20170602_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSyncFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='buildingsync_files')),
                ('file_size_in_bytes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('category_display_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='PropertyMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_status', models.IntegerField(choices=[(1, 'Recommended'), (2, 'Proposed'), (3, 'Implemented')], default=1)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.Measure')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='simulation_files')),
                ('file_size_in_bytes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('property_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seed.PropertyState')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='meter',
            name='building_snapshot',
        ),
        migrations.AddField(
            model_name='meter',
            name='property_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='seed.PropertyView'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='orgs.Organization'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.Meter'),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='seed.Simulation'),
        ),
        migrations.AddField(
            model_name='propertymeasure',
            name='property_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.PropertyState'),
        ),
        migrations.AddField(
            model_name='buildingsyncfile',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingsync_file', to='seed.PropertyState'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='begin_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='timeseries',
            index_together=set([('begin_time', 'end_time')]),
        ),
    ]
