# Generated by Django 1.9.13 on 2017-06-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0068_auto_20170614_1150"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="propertyauditlog",
            index=models.Index(fields=["state", "name"], name="seed_propertyauditlog_state_id_name_679dbf00_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyauditlog",
            index=models.Index(
                fields=["parent_state1", "parent_state2"], name="seed_propertyauditlog_parent_state1_id_parent__06124cd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertystate",
            index=models.Index(
                fields=["import_file", "data_state", "merge_state"], name="seed_propertystate_import_file_id_data_stat_d916805d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxlotauditlog",
            index=models.Index(fields=["state", "name"], name="seed_taxlotauditlog_state_id_name_e197747e_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotauditlog",
            index=models.Index(fields=["parent_state1", "parent_state2"], name="seed_taxlotauditlog_parent_state1_id_parent__643a0792_idx"),
        ),
        migrations.AddIndex(
            model_name="taxlotstate",
            index=models.Index(
                fields=["import_file", "data_state", "merge_state"], name="seed_taxlotstate_import_file_id_data_stat_5703bcf2_idx"
            ),
        ),
    ]
