# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-14 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0068_auto_20170614_1150'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='propertyauditlog',
            index_together=set([('state', 'name'), ('parent_state1', 'parent_state2')]),
        ),
        migrations.AlterIndexTogether(
            name='propertystate',
            index_together=set([('import_file', 'data_state'), ('import_file', 'data_state', 'merge_state')]),
        ),
        migrations.AlterIndexTogether(
            name='taxlotauditlog',
            index_together=set([('state', 'name'), ('parent_state1', 'parent_state2')]),
        ),
        migrations.AlterIndexTogether(
            name='taxlotstate',
            index_together=set([('import_file', 'data_state'), ('import_file', 'data_state', 'merge_state')]),
        ),
    ]
