# Generated by Django 1.9.13 on 2017-06-21 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0068_green_assessments"),
        ("seed", "0069_auto_20170614_1430"),
    ]

    operations = []
