# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0070_auto_20170621_1410'),
        ('seed', '0070_merge'),
    ]

    operations = [
    ]
