# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-20 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0073_column_units_pint'),
        ('seed', '0072_auto_20170918_0850'),
    ]

    operations = [
    ]
