# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0074_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncanonicalprojectbuildings',
            name='projectbuilding',
        ),
        migrations.AlterUniqueTogether(
            name='projectbuilding',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectbuilding',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='projectbuilding',
            name='building_snapshot',
        ),
        migrations.RemoveField(
            model_name='projectbuilding',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='building_snapshots',
        ),
        migrations.AlterField(
            model_name='rule',
            name='data_type',
            field=models.IntegerField(choices=[(0, b'number'), (1, b'string'), (2, b'date'), (3, b'year'), (4, b'area'), (5, b'eui')], null=True),
        ),
        migrations.DeleteModel(
            name='NonCanonicalProjectBuildings',
        ),
        migrations.DeleteModel(
            name='ProjectBuilding',
        ),
    ]
