# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0077_auto_20171024_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfile',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'BuildingSync'), (2, 'GeoJSON'), (3, 'HPXML')], default=0),
        ),
    ]
