# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0077_auto_20171024_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertymeasure',
            unique_together=set([('property_state', 'measure', 'application_scale', 'implementation_status')]),
        ),
    ]
