# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0080_column_shared_field_type'),
        ('seed', '0080_auto_20180107_0808'),
    ]

    operations = [
    ]
