# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 18:33
from __future__ import unicode_literals

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0081_merge_20180109_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='source_eui_modeled_pint',
            field=quantityfield.fields.QuantityField(base_units='kBtu/ft**2/year', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='site_eui_modeled_pint',
            field=quantityfield.fields.QuantityField(base_units='kBtu/ft**2/year', blank=True, null=True),
        ),
    ]
