# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0082_propertystate_source_eui_modeled_pint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertystate',
            old_name='conditioned_floor_area',
            new_name='conditioned_floor_area_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='gross_floor_area',
            new_name='gross_floor_area_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='occupied_floor_area',
            new_name='occupied_floor_area_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='site_eui_modeled',
            new_name='site_eui_modeled_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='site_eui',
            new_name='site_eui_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='site_eui_weather_normalized',
            new_name='site_eui_weather_normalized_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='source_eui',
            new_name='source_eui_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='source_eui_modeled',
            new_name='source_eui_modeled_orig',
        ),
        migrations.RenameField(
            model_name='propertystate',
            old_name='source_eui_weather_normalized',
            new_name='source_eui_weather_normalized_orig',
        ),
    ]
