# Generated by Django 1.11.6 on 2018-01-23 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0082_auto_20180119_1021'),
        ('seed', '0086_auto_20180111_1531'),
    ]

    operations = []
