# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_organization_display_significant_figures'),
        ('seed', '0087_merge_20180123_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnListSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('settings_location', models.IntegerField(choices=[(0, b'List View Settings'), (1, b'Detail View Settings')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnListSettingColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Column')),
                ('column_list_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.ColumnListSetting')),
            ],
        ),
        migrations.AddField(
            model_name='columnlistsetting',
            name='columns',
            field=models.ManyToManyField(through='seed.ColumnListSettingColumn', to='seed.Column'),
        ),
        migrations.AddField(
            model_name='columnlistsetting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
    ]
