# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_organization_display_significant_figures'),
        ('seed', '0087_merge_20180123_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnListSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('columns', models.ManyToManyField(to='seed.Column')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
    ]
