# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0088_auto_20180423_0933'),
        ('seed', '0088_auto_20180420_1238'),
    ]

    operations = [
    ]
