# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0089_merge_20180425_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_type',
            field=models.CharField(default=b'None', max_length=64),
        ),
        migrations.AddField(
            model_name='column',
            name='display_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='columnlistsetting',
            name='columns',
            field=models.ManyToManyField(related_name='column_list_settings', through='seed.ColumnListSettingColumn', to='seed.Column'),
        ),
    ]
