# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 14:12
from __future__ import unicode_literals

from django.db import migrations


from seed.models.columns import Column as ColumnModel


def forwards(apps, schema_editor):
    Column = apps.get_model("seed", "Column")
    Organization = apps.get_model("orgs", "Organization")

    # from seed.lib.superperms.orgs.models import (
    db_fields = ColumnModel.DATABASE_COLUMNS

    # Go through all the organizatoins
    for org in Organization.objects.all():
    # for org in Organization.objects.filter(id=1):
        print "Checking for missing columns for %s" % org.id
        details = {
            'organization_id': org.id,
        }
        for field in db_fields:
            # check if the db field exists in the database.
            columns = Column.objects.filter(
                organization_id=org.id,
                table_name=field['table_name'],
                column_name=field['column_name'],
                is_extra_data=False,
            )

            # print "column is %s:%s" % (columns[0].table_name, columns[0].column_name)
            if not columns.count():
                # print "  Adding in new column: %s" % field
                details.update(field)
                Column.objects.create(**details)
            elif columns.count() == 1:
                c = columns.first()
                # update the display name and data_type if it is not already defined
                # print "  Found one column: %s" % c.id
                if c.display_name is None or c.display_name == '':
                    # print "  Changing display_name %s to %s" % (c.display_name, field['display_name'])
                    c.display_name = field['display_name']
                if c.data_type is None or c.data_type == '' or c.data_type == 'None':
                    # print "  Adding data_type %s to %s" % (c.data_type, field['data_type'])
                    c.data_type = field['data_type']
                c.save()
            else:
                print "  More than one column returned"
                # raise Exception("More than one column returned in migration: %s" % field)


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0090_auto_20180425_1154'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
