# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0090_auto_20180508_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertystate',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='taxlotstate',
            name='confidence',
        ),
    ]
