# Generated by Django 1.11.6 on 2018-07-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0006_organization_display_significant_figures"),
        ("data_importer", "0011_auto_20180725_0825"),
        ("seed", "0090_auto_20180508_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertystate",
            name="hash_object",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="taxlotstate",
            name="hash_object",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_type",
            field=models.IntegerField(choices=[(1, b"String"), (6, b"Integer"), (3, b"Float"), (4, b"Date"), (5, b"Datetime")], default=1),
        ),
        migrations.RemoveField(
            model_name="propertystate",
            name="confidence",
        ),
        migrations.AddIndex(
            model_name="propertystate",
            index=models.Index(fields=["hash_object"], name="seed_propertystate_hash_object_506634f0_idx"),
        ),
        migrations.RemoveField(
            model_name="taxlotstate",
            name="confidence",
        ),
        migrations.AddIndex(
            model_name="taxlotstate",
            index=models.Index(fields=["hash_object"], name="seed_taxlotstate_hash_object_274336bb_idx"),
        ),
    ]
