# Generated by Django 1.11.6 on 2018-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0006_organization_display_significant_figures"),
        ("data_importer", "0011_auto_20180725_0825"),
        ("seed", "0092_add_hash_object_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="propertystate",
            index=models.Index(
                fields=["import_file", "data_state", "source_type"], name="seed_propertystate_import_file_id_data_stat_d8ed8145_idx"
            ),
        ),
    ]
