# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0096_auto_20181107_0904'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS audit_logs_auditlog;'),
        migrations.RunSQL('DROP TABLE IF EXISTS seed_attributeoption;'),
        migrations.RunSQL('DROP TABLE IF EXISTS seed_buildingattributevariant;'),
    ]
