# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 21:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0097_auto_20181107_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='long_lat',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='long_lat',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
