# Generated by Django 1.11.18 on 2019-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0098_auto_20181121_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfile',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'BuildingSync'), (3, 'HPXML')], default=0),
        ),
    ]
