# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0098_auto_20181121_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='property_view',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='scenario',
        ),
        migrations.AlterIndexTogether(
            name='timeseries',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='meter',
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
        migrations.DeleteModel(
            name='TimeSeries',
        ),
    ]
