# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 22:53
from __future__ import unicode_literals

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0099_auto_20190129_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(1, 'Property Manager'), (2, 'GreenButton'), (3, 'BuildingSync')])),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Coal (anthracite)'), (2, 'Coal (bituminous)'), (3, 'Coke'), (4, 'Diesel'), (5, 'District Chilled Water'), (6, 'District Hot Water'), (7, 'District Steam'), (8, 'Electricity'), (9, 'Electricity - on site renewable'), (10, 'Fuel Oil (No. 1)'), (11, 'Fuel Oil (No. 2)'), (12, 'Fuel Oil (No. 4)'), (13, 'Fuel Oil (No. 5 & No. 6)'), (14, 'Kerosene'), (15, 'Natural Gas'), (16, 'Other'), (17, 'Propane and Liquid Propane'), (18, 'Wood')])),
                ('units', models.IntegerField(choices=[(1, 'kBtu')])),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='seed.Property')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('start_time', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('reading', models.FloatField(null=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='seed.Meter')),
            ],
        ),
        CreateExtension('timescaledb'),
        migrations.RunSQL("ALTER TABLE seed_meterreading DROP CONSTRAINT seed_meterreading_pkey"),
        migrations.RunSQL("SELECT create_hypertable('seed_meterreading', 'start_time');"),
        migrations.AlterUniqueTogether(
            name='meterreading',
            unique_together=set([('meter', 'start_time', 'end_time')]),
        ),
    ]
