# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 16:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0099_auto_20190107_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='bounding_box',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='bounding_box',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
