# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 23:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0100_auto_20190118_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
