# Generated by Django 1.11.21 on 2019-07-02 21:00

# Developer note: it is known that the id of this is similar to the one above (0105) and is this case
# because two branches both made migrations. Unfortunately, this wasn't caught until too late as the
# migrations were run on a production database, ergo, we kept this as is and have a merge downstream.


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0104_auto_20190509_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="annual_electricity_energy",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="annual_electricity_savings",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="annual_natural_gas_energy",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="annual_natural_gas_savings",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="annual_peak_demand",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="annual_site_energy",
            field=models.FloatField(null=True),
        ),
    ]
