# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0105_auto_20190613_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='reading',
            field=models.FloatField(null=True),
        ),
    ]
