# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models, transaction


def forwards(apps, schema_editor):
    Column = apps.get_model("seed", "Column")

    with transaction.atomic():
        original_identity_fields = [
            'address_line_1',  # Technically this was normalized_address, but matching logic handles this as such
            'custom_id_1',
            'pm_property_id',
            'jurisdiction_tax_lot_id',
            'ubid',
            'ulid'
        ]
        Column.objects.filter(column_name__in=original_identity_fields).update(is_matching_criteria=True)


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0105_auto_20190613_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_matching_criteria',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards),
    ]
