# Generated by Django 1.11.21 on 2019-07-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0105_auto_20190702_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="scenario_id",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="seed.Scenario"),
        ),
    ]
