# Generated by Django 1.11.21 on 2019-07-10 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0106_meter_scenario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='scenario_id',
            new_name='scenario',
        ),
    ]
