# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0105_auto_20190613_1251'),
        ('seed', '0107_auto_20190709_2058'),
    ]

    operations = [
    ]
