# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 19:12
from __future__ import unicode_literals

from django.db import connection, migrations, models
import django.utils.timezone


def forwards(apps, schema_editor):
    property_sql = (
        "UPDATE seed_propertystate " +
        "SET created = seed_propertyauditlog.created, updated = seed_propertyauditlog.created " +
        "FROM seed_propertyauditlog " +
        "WHERE seed_propertystate.id = state_id;"
    )

    taxlot_sql = (
        "UPDATE seed_taxlotstate " +
        "SET created = seed_taxlotauditlog.created, updated = seed_taxlotauditlog.created " +
        "FROM seed_taxlotauditlog " +
        "WHERE seed_taxlotstate.id = state_id;"
    )

    with connection.cursor() as cursor:
        cursor.execute(property_sql)
        cursor.execute(taxlot_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0108_column_is_matching_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(forwards),
    ]
