# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-24 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0110_auto_20200323_1509'),
        ('seed', '0110_auto_20200303_1428'),
    ]

    operations = [
    ]
