# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-11 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20190714_2159'),
        ('seed', '0112_refresh_matching_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMappingPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mappings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
