# Generated by Django 1.11.23 on 2019-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0113_column_geocoding_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.IntegerField(choices=[(0, 'error'), (1, 'warning'), (2, 'valid')], default=0),
        ),
    ]
