# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20190714_2159'),
        ('seed', '0113_columnmappingpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmappingpreset',
            name='organizations',
            field=models.ManyToManyField(to='orgs.Organization'),
        ),
    ]
