# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0118_match_merge_link_all_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='recognize_empty',
            field=models.BooleanField(default=False),
        ),
    ]
