# Generated by Django 2.0.13 on 2020-02-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0118_match_merge_link_all_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
