# Generated by Django 2.2.10 on 2020-03-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0121_auto_20200304_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='condition',
        ),
    ]
