# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0122_auto_20200303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmapping',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Assessed Raw'), (2, 'Assessed'), (1, 'Portfolio Raw'), (3, 'Portfolio'), (4, 'BuildingSnapshot'), (5, 'BuildingSync Raw')], null=True),
        ),
    ]
