# Generated by Django 2.2.10 on 2020-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0122_column_recognize_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rule',
            name='placeholder',
            field=models.CharField(default='(field must contain this text)', max_length=200),
        ),
    ]
