# Generated by Django 2.2.10 on 2020-06-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0126_columnmappingpreset_preset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='comstock_mapping',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
