# Generated by Django 2.2.13 on 2020-08-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_organization_comstock_enabled'),
        ('seed', '0127_auto_20200605_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColumnMappingPreset',
            new_name='ColumnMappingProfile',
        ),
        migrations.RenameField(
            model_name='columnmappingprofile',
            old_name='preset_type',
            new_name='profile_type',
        ),
    ]
