# Generated by Django 2.2.13 on 2020-08-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0128_auto_20200810_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnmappingprofile',
            old_name='preset_type',
            new_name='profile_type',
        ),
    ]
