# Generated by Django 2.2.13 on 2020-08-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_organization_comstock_enabled'),
        ('seed', '0128_auto_20200810_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColumnListSetting',
            new_name='ColumnListProfile',
        ),
    ]
