# Generated by Django 2.2.13 on 2020-08-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0129_auto_20200828_0610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColumnListSettingColumn',
            new_name='ColumnListProfileColumn',
        ),
        migrations.RenameField(
            model_name='columnlistprofile',
            old_name='settings_location',
            new_name='profile_location',
        ),
        migrations.RenameField(
            model_name='columnlistprofilecolumn',
            old_name='column_list_setting',
            new_name='column_list_profile',
        ),
    ]
