# Generated by Django 2.2.13 on 2020-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0130_auto_20200828_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnlistprofile',
            name='columns',
            field=models.ManyToManyField(related_name='column_list_profiles', through='seed.ColumnListProfileColumn', to='seed.Column'),
        ),
        migrations.AlterField(
            model_name='columnlistprofile',
            name='profile_location',
            field=models.IntegerField(choices=[(0, 'List View Profile'), (1, 'Detail View Profile')], default=0),
        ),
    ]
