# Generated by Django 2.2.13 on 2020-12-11 19:49

from django.db import migrations, models
import seed.models.analysis_input_files


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0131_analysis_analysisinputfile_analysismessage_analysisoutputfile_analysispropertyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisinputfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=seed.models.analysis_input_files.analysis_input_path),
        ),
    ]
