# Generated by Django 2.2.13 on 2020-12-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0132_auto_20201211_1949_squashed_0134_auto_20201211_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisinputfile',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='seed.Analysis'),
        ),
    ]
