# Generated by Django 2.2.13 on 2020-11-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0132_analysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='analysis_files')),
                ('file_type', models.IntegerField(choices=[(1, 'BuildingSync')])),
                ('input_for_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='seed.AnalysisRun')),
                ('output_for_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='seed.AnalysisRun')),
            ],
        ),
    ]
