# Generated by Django 2.2.13 on 2021-01-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0134_auto_20201217_2236'),
        ('seed', '0128_auto_20210119_1238'),
    ]

    operations = [
    ]
