# Generated by Django 2.2.13 on 2021-01-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0135_auto_20210112_2306'),
        ('seed', '0128_auto_20210119_1238'),
    ]

    operations = [
    ]
