# Generated by Django 2.2.13 on 2021-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0136_merge_20210120_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslabel',
            name='show_in_list',
            field=models.BooleanField(default=False),
        ),
    ]
