# Generated by Django 2.2.20 on 2021-05-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_auto_20210218_1715'),
        ('seed', '0137_statuslabel_show_in_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventory_type', models.IntegerField(choices=[(0, 'Property'), (1, 'Tax Lot')])),
                ('expression', models.CharField(max_length=526)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedColumnParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50)),
                ('derived_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.DerivedColumn')),
                ('source_column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Column')),
            ],
        ),
        migrations.AddField(
            model_name='derivedcolumn',
            name='source_columns',
            field=models.ManyToManyField(through='seed.DerivedColumnParameter', to='seed.Column'),
        ),
        migrations.AddConstraint(
            model_name='derivedcolumnparameter',
            constraint=models.UniqueConstraint(fields=('derived_column', 'parameter_name'), name='unique_parameter_name'),
        ),
        migrations.AddConstraint(
            model_name='derivedcolumnparameter',
            constraint=models.UniqueConstraint(fields=('derived_column', 'source_column'), name='unique_reference_to_source_column'),
        ),
        migrations.AddConstraint(
            model_name='derivedcolumn',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_name_for_organization'),
        ),
    ]
