# Generated by Django 2.2.13 on 2020-12-08 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_organization_comstock_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_office', '0011_models_help_text'),
        ('seed', '0138_auto_20201027_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOfficeEmailTemplate',
            fields=[
                ('emailtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post_office.EmailTemplate')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('post_office.emailtemplate',),
        ),
        migrations.CreateModel(
            name='PostOfficeEmail',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post_office.Email')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('post_office.email',),
        ),
    ]
