# Generated by Django 2.2.20 on 2021-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0138_auto_20210512_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymeasure',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
