# Generated by Django 2.2.20 on 2021-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0139_auto_20210524_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymeasure',
            name='useful_life',
            field=models.FloatField(null=True),
        ),
    ]
