# Generated by Django 2.2.20 on 2021-06-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0139_auto_20210524_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='annual_peak_electricity_reduction',
            field=models.FloatField(null=True),
        ),
    ]
