# Generated by Django 2.2.13 on 2021-06-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0143_auto_20210614_2058'),
        ('seed', '0142_merge_20210611_0610'),
    ]

    operations = [
    ]
