# Generated by Django 2.2.20 on 2021-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0144_merge_20210615_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='for_derived_column',
            field=models.BooleanField(default=False),
        ),
    ]
