# Generated by Django 2.2.13 on 2021-06-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0140_postofficeemail_postofficeemailtemplate'),
        ('seed', '0144_merge_20210615_1322'),
    ]

    operations = [
    ]
