# Generated by Django 2.2.24 on 2021-06-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0145_rule_for_derived_column'),
        ('seed', '0145_merge_20210621_0716'),
    ]

    operations = [
    ]
