# Generated by Django 3.0.14 on 2021-07-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0147_rename_bsync_col_mapping_preset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliance',
            options={'ordering': ('-modified', '-created')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-modified', '-created')},
        ),
    ]
