# Generated by Django 3.1.13 on 2021-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0148_auto_20210712_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='service',
            field=models.IntegerField(choices=[(1, 'BSyncr'), (2, 'BETTER'), (3, 'EUI')]),
        ),
    ]
