# Generated by Django 3.2.12 on 2022-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0159_auto_20220310_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='is_occupied_data',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_occupied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
