# Generated by Django 3.2.12 on 2022-03-31 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0159_auto_20220310_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoggerLocationIsOccupied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occuppied', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('data_logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_occupied', to='seed.datalogger')),
            ],
            options={
                'unique_together': {('timestamp', 'data_logger')},
            },
        ),
    ]
