# Generated by Django 3.2.12 on 2022-04-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0159_auto_20220310_1648'),
        ('seed', '0159_inventorydocument'),
    ]

    operations = [
    ]
