# Generated by Django 3.2.12 on 2022-04-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0160_auto_20220412_0025'),
        ('seed', '0161_alter_inventorydocument_file_type'),
    ]

    operations = [
    ]
