# Generated by Django 3.2.12 on 2022-04-29 16:24

from django.db import migrations, models


def forwards(apps, schema_editor):
    Column = apps.get_model("seed", "Column")
    Organization = apps.get_model("orgs", "Organization")

    # Go through all the organizations
    for org in Organization.objects.all():
        columns = Column.objects.filter(organization_id=org.id)

        for col in columns:
            if col.display_name is None or col.display_name == "":
                col.new_column = col.column_name
            else:
                col.new_column = col.display_name
            col.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0161_alter_inventorydocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='new_column',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(forwards)
    ]
