# Generated by Django 3.2.12 on 2022-05-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0162_auto_20220418_2257'),
        ('seed', '0162_column_new_column'),
    ]

    operations = [
    ]
