# Generated by Django 3.2.13 on 2022-05-10 20:08

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0163_add_bae_assets_to_buildingsync_default_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='total_ghg_emissions',
            field=quantityfield.fields.QuantityField(base_units='MtCO2e/year', blank=True, null=True, unit_choices=['MtCO2e/year']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='total_ghg_emissions_intensity',
            field=quantityfield.fields.QuantityField(base_units='kgCO2e/ft**2/year', blank=True, null=True, unit_choices=['kgCO2e/ft**2/year']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='total_marginal_ghg_emissions',
            field=quantityfield.fields.QuantityField(base_units='MtCO2e/year', blank=True, null=True, unit_choices=['MtCO2e/year']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='total_marginal_ghg_emissions_intensity',
            field=quantityfield.fields.QuantityField(base_units='kgCO2e/ft**2/year', blank=True, null=True, unit_choices=['kgCO2e/ft**2/year']),
        ),
    ]
