# Generated by Django 3.2.13 on 2022-05-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0164_derivedcolumnparameter_source_column_derived'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='derived_column',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.derivedcolumn'),
        ),
        migrations.AddField(
            model_name='column',
            name='derived_column_type',
            field=models.BooleanField(default=False),
        ),
    ]
