# Generated by Django 3.2.13 on 2022-04-29 20:40

from django.db import migrations, models, transaction


def forwards(apps, schema_editor):
    Column = apps.get_model("seed", "Column")
    Organization = apps.get_model("orgs", "Organization")

    with transaction.atomic():
        # Go through all the organizations
        for org in Organization.objects.all():
            columns = Column.objects.filter(organization_id=org.id)

            for col in columns:
                if col.display_name is None or col.display_name == "":
                    col.column_description = col.column_name
                else:
                    col.column_description = col.display_name
                col.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0164_auto_20220510_2008'),
    ]

    operations = [
        # don't enforce null at the beginning because the data haven't migrated yet
        migrations.AddField(
            model_name='column',
            name='column_description',
            field=models.TextField(blank=True, null=True, default=None, max_length=1000),
        ),
        migrations.RunPython(forwards),
        # Now enforce null
        migrations.AlterField(
            model_name='column',
            name='column_description',
            field=models.TextField(blank=True, default=None, max_length=1000),
        ),
    ]
