# Generated by Django 3.2.13 on 2022-05-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0164_auto_20220510_2008'),
        ('seed', '0164_column_column_description'),
    ]

    operations = [
    ]
