# Generated by Django 3.2.13 on 2022-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0166_auto_20220606_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='identifier',
            field=models.CharField(default='', max_length=2047),
        ),
    ]
