# Generated by Django 3.2.13 on 2022-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0170_column_derived_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='audit_template_building_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
