# Generated by Django 3.2.14 on 2022-08-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_auto_20220721_1851'),
        ('seed', '0174_fix_ghg_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('filter_group', models.JSONField()),
                ('column1_aggregations', models.JSONField(default=None)),
                ('column2_aggregations', models.JSONField(default=None)),
                ('columns', models.ManyToManyField(to='seed.Column')),
                ('cycles', models.ManyToManyField(to='seed.Cycle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
    ]
