# Generated by Django 3.2.14 on 2022-09-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_auto_20220721_1851'),
        ('seed', '0175_filtergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cycles', models.ManyToManyField(to='seed.Cycle')),
                ('filter_groups', models.ManyToManyField(to='seed.FilterGroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DataViewParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('aggregations', models.JSONField(blank=True)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.column')),
                ('data_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='seed.dataview')),
            ],
        ),
    ]
