# Generated by Django 3.2.14 on 2022-09-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_auto_20220721_1851'),
        ('seed', '0176_dataview_dataviewparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('energy_metric_type', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Target > Actual for Compliance'), (2, 'Actual > Target for Compliance')], null=True)),
                ('emission_metric_type', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Target > Actual for Compliance'), (2, 'Actual > Target for Compliance')], null=True)),
                ('actual_emission_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_emission_column', to='seed.column')),
                ('actual_energy_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_energy_column', to='seed.column')),
                ('filter_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_group', to='seed.filtergroup')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_metrics', to='orgs.organization')),
                ('target_emission_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_emission_column', to='seed.column')),
                ('target_energy_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_energy_column', to='seed.column')),
                ('x_axis_columns', models.ManyToManyField(blank=True, related_name='x_axis_columns', to='seed.Column')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
    ]
