# Generated by Django 3.2.14 on 2022-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0178_compliance_metric_type_not_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemetric',
            name='emission_metric_type',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Target > Actual for Compliance'), (2, 'Actual > Target for Compliance')], null=True),
        ),
        migrations.AlterField(
            model_name='compliancemetric',
            name='energy_metric_type',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Target > Actual for Compliance'), (2, 'Actual > Target for Compliance')], null=True),
        ),
    ]
