# Generated by Django 3.2.14 on 2022-11-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0179_auto_20220916_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancemetric',
            name='filter_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_group', to='seed.filtergroup'),
        ),
    ]
