# Generated by Django 3.2.14 on 2022-11-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0180_compliancemetric_filter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemetric',
            name='x_axis_columns',
            field=models.ManyToManyField(null=True, related_name='x_axis_columns', to='seed.Column'),
        ),
    ]
