# Generated by Django 3.2.16 on 2022-12-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0180_remove_property_campus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compliancemetric',
            name='at_least_one_compliance_metric_type',
        ),
        migrations.AddField(
            model_name='compliancemetric',
            name='filter_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_group', to='seed.filtergroup'),
        ),
        migrations.AlterField(
            model_name='compliancemetric',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancemetric',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancemetric',
            name='x_axis_columns',
            field=models.ManyToManyField(blank=True, related_name='x_axis_columns', to='seed.Column'),
        ),
    ]
