# Generated by Django 3.2.16 on 2022-12-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0180_remove_property_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='source',
            field=models.IntegerField(choices=[(1, 'Portfolio Manager'), (2, 'GreenButton'), (3, 'BuildingSync'), (4, 'Portfolio Manager'), (5, 'Manual Entry')], default=None, null=True),
        ),
    ]
