# Generated by Django 3.2.14 on 2022-11-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0181_alter_compliancemetric_x_axis_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemetric',
            name='x_axis_columns',
            field=models.ManyToManyField(blank=True, related_name='x_axis_columns', to='seed.Column'),
        ),
    ]
