# Generated by Django 3.2.14 on 2022-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0182_alter_compliancemetric_x_axis_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemetric',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancemetric',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
