# Generated by Django 3.2.13 on 2023-02-01 21:45

from django.db import migrations, models


def forwards(apps, schema_editor):
    Organization = apps.get_model("orgs", "Organization")

    # we added a few new types of meters that need default
    # units. This will add them to all existing orgs.
    for org in Organization.objects.all():
        # if the keys don't exist, add them
        if "Default" not in org.display_meter_units:
            org.display_meter_units["Default"] = "kBtu (thousand Btu)"
        if "District Chilled Water" not in org.display_meter_units:
            org.display_meter_units["District Chilled Water"] = "kBtu (thousand Btu)"
        if "Electric" not in org.display_meter_units:
            org.display_meter_units["Electric"] = "kWh (thousand Watt-hours)"
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0183_auto_20221216_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='type',
            field=models.IntegerField(choices=[(1, 'Coal (anthracite)'), (2, 'Coal (bituminous)'), (3, 'Coke'), (4, 'Diesel'), (25, 'District Chilled Water'), (5, 'District Chilled Water - Absorption'), (6, 'District Chilled Water - Electric'), (7, 'District Chilled Water - Engine'), (8, 'District Chilled Water - Other'), (9, 'District Hot Water'), (10, 'District Steam'), (26, 'Electric'), (11, 'Electric - Grid'), (12, 'Electric - Solar'), (13, 'Electric - Wind'), (14, 'Fuel Oil (No. 1)'), (15, 'Fuel Oil (No. 2)'), (16, 'Fuel Oil (No. 4)'), (13, 'Fuel Oil (No. 5 and No. 6)'), (18, 'Kerosene'), (19, 'Natural Gas'), (20, 'Other:'), (21, 'Propane'), (22, 'Wood'), (23, 'Cost'), (24, 'Electric - Unknown'), (99, 'Custom Meter')], default=None, null=True),
        ),
        migrations.RunPython(forwards)
    ]
