# Generated by Django 3.2.14 on 2022-11-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0183_auto_20221118_0854'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compliancemetric',
            name='at_least_one_compliance_metric_type',
        ),
    ]
