# Generated by Django 3.2.17 on 2023-03-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0185_auto_20230112_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancemetric',
            name='end',
        ),
        migrations.RemoveField(
            model_name='compliancemetric',
            name='start',
        ),
        migrations.AddField(
            model_name='compliancemetric',
            name='cycles',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='seed.Cycle'),
        ),
    ]
