# Generated by Django 3.2.17 on 2023-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0186_salesforce_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceconfig',
            name='update_at_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesforceconfig',
            name='update_at_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='salesforceconfig',
            constraint=models.CheckConstraint(check=models.Q(('update_at_hour__range', (0, 23))), name='salesforce_update_at_hour_range'),
        ),
        migrations.AddConstraint(
            model_name='salesforceconfig',
            constraint=models.CheckConstraint(check=models.Q(('update_at_minute__range', (0, 59))), name='salesforce_update_at_minute_range'),
        ),
    ]
