# Generated by Django 3.2.18 on 2023-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0186_salesforce_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancemetric',
            name='end',
        ),
        migrations.RemoveField(
            model_name='compliancemetric',
            name='start',
        ),
        migrations.AddField(
            model_name='compliancemetric',
            name='cycles',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='seed.Cycle'),
        ),
    ]
