# Generated by Django 3.2.18 on 2023-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0187_backfill_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='atevent',
            name='audit_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
