# Generated by Django 3.2.18 on 2023-04-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0191_add_data_admin_to_sf'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceconfig',
            name='data_admin_account_name_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_admin_account_name_column', to='seed.column'),
        ),
        migrations.AddField(
            model_name='salesforceconfig',
            name='default_contact_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesforceconfig',
            name='default_data_admin_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
