# Generated by Django 3.2.18 on 2023-05-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0194_alter_taxlotview_taxlot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertystate',
            old_name='ubid',
            new_name='ubid_dead',
        ),
        migrations.CreateModel(
            name='Ubid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubid', models.CharField(max_length=255)),
                ('preferred', models.BooleanField(default=False)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.propertystate')),
                ('taxlot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.taxlotstate')),

            ],
        ),
    ]
