# Generated by Django 3.2.19 on 2023-06-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0195_sf_delete_label_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnmapping',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Assessed Raw'), (1, 'Portfolio Raw'), (2, 'Assessed'), (3, 'Portfolio'), (4, 'BuildingSnapshot'), (5, 'BuildingSync Raw'), (6, 'GreenButton'), (7, 'PM Meter Usage'), (8, 'SensorMetadata'), (9, 'SensorReadings')], db_index=True, null=True),
        ),
    ]
