# Generated by Django 3.2.18 on 2023-05-08 21:13

from django.db import migrations, models, transaction
import django.db.models.deletion

@transaction.atomic
def backfill_ubids(apps, schema_editor):
    PropertyState = apps.get_model("seed", "PropertyState")
    TaxLotState = apps.get_model("seed", "TaxLotState")
    Ubid = apps.get_model("seed", "Ubid")

    property_states = PropertyState.objects.all()
    for state in property_states:
        ubid = Ubid.objects.create(
            ubid = state.ubid_dead,
            property=state,
            preferred=True,
        )
        ubid.save()
    
    taxlot_states = TaxLotState.objects.all()
    for state in taxlot_states:
        ubid = Ubid.objects.create(
            ubid = state.ulid,
            taxlot=state,
            preferred=True,
        )
        ubid.save()
class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0195_sf_delete_label_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertystate',
            old_name='ubid',
            new_name='ubid_dead',
        ),
        migrations.CreateModel(
            name='Ubid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubid', models.CharField(max_length=255)),
                ('preferred', models.BooleanField(default=False)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.propertystate')),
                ('taxlot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.taxlotstate')),

            ],
        ),
        migrations.RunPython(backfill_ubids),
        migrations.RemoveField(
            model_name='propertystate',
            name='ubid_dead',
        ),

    ]
