# Generated by Django 3.2.19 on 2023-06-09 13:43

from django.db import migrations, models, transaction

class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0195_sf_delete_label_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start',
            field=models.DateField(),
        )
    ]
