# Generated by Django 3.2.19 on 2023-05-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0195_sf_delete_label_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxlotstate',
            old_name='ulid',
            new_name='ubid',
        ),
    ]
