# Generated by Django 3.2.17 on 2023-03-11 00:30

from django.db import migrations
from django.db import transaction

@transaction.atomic
def backfill_ubids(apps, schema_editor):
    PropertyState = apps.get_model("seed", "PropertyState")
    TaxLotState = apps.get_model("seed", "TaxLotState")
    Ubid = apps.get_model("seed", "Ubid")

    property_states = PropertyState.objects.all()
    for state in property_states:
        ubid = Ubid.objects.create(
            ubid = state.ubid_dead,
            property=state,
            preferred=True,
        )
        ubid.save()
    
    taxlot_states = TaxLotState.objects.all()
    for state in taxlot_states:
        ubid = Ubid.objects.create(
            ubid = state.ulid,
            taxlot=state,
            preferred=True,
        )
        ubid.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0195_auto_20230508_1413'),
    ]

    operations = [
        migrations.RunPython(backfill_ubids)
    ]

