# Generated by Django 3.2.19 on 2023-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0196_remove_time_from_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
