# Generated by Django 3.2.19 on 2023-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0197_pm_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start',
            field=models.DateField(),
        ),
    ]
