# Generated by Django 1.9.5 on 2017-01-19 21:18

from django.db import migrations

from seed.utils.migrations import rehash


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0199_rename_ulid_taxlotstate_ubid"),
    ]

    operations = [
        migrations.RunPython(lambda apps, _schema_editor: rehash(apps)),
    ]
