# Generated by Django 3.2.19 on 2023-05-15 17:38

from pathlib import Path

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0201_ubidmodel'),
    ]

    ubid_root = Path(__file__).parent.parent / 'ubid'

    operations = [
        migrations.RunSQL(
            (ubid_root / 'pluscode_functions.sql').read_text(),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            (ubid_root / 'buildingid_functions.sql').read_text(),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            (ubid_root / 'buildingid_postgis_functions.sql').read_text(),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
