# Generated by Django 3.2.20 on 2023-07-17 20:14

from django.db import migrations, models, transaction

def forwards(apps, schema_editor):
    """Before pint units were in columns, there might exist a 
    case where a mapping raw column is in the database twice. Check
    which of these are being mapped, then delete the unmapped one."""
    Column = apps.get_model("seed", "Column")

    # find the duplicate columns with a database query
    duplicate_columns = Column.objects.values('organization', 'column_name', 'table_name', 'is_extra_data', 'units_pint') \
        .annotate(column_count=models.Count('id')) \
        .filter(column_count__gt=1)
    
    errors_found = False
    for dup_col in duplicate_columns:
        errors_found = True
        print(f"Found a duplicate set of columns for org {dup_col['organization']}. "
              f"With table_name '{dup_col['table_name']}', column_name '{dup_col['column_name']}', "
              f"is_extra_data '{dup_col['is_extra_data']}, units_pint {dup_col['units_pint']}'.")
        
        # find the columns that are not mapped to any column mapping profiles
        # unmapped_columns = Column.objects.filter(
        #     organization=dup_col['organization'],
        #     column_name=dup_col['column_name'],
        #     table_name=dup_col['table_name'],
        #     is_extra_data=dup_col['is_extra_data'],
        #     units_pint=dup_col['units_pint'],
    
    if errors_found:
        print("Please delete the duplicate columns manually, then run the migration again.")
        # you can see an example on how to retrieve the duplicate columns here above. 
        # verify that the columns you are deleting are not mapped to any column mapping profiles
        exit(1)
        
class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0202_ubid_sql_functions'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('organization', 'column_name', 'table_name', 'is_extra_data', 'units_pint'), name='unique_column_name'),
        ),
    ]
