# Generated by Django 3.2.20 on 2023-09-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0203_column_unique_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atevent',
            name='building_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.buildingfile'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='seed.atevent'),
        ),
    ]
