# Generated by Django 3.2.18 on 2023-04-17 21:17

from django.db import migrations, models
import django.db.models.deletion
from django.db import transaction


@transaction.atomic
def assign_properties_to_root_acces_level(apps, schema_editor):
    Property = apps.get_model('seed', 'Property')
    AccessLevelInstance = apps.get_model('orgs', 'AccessLevelInstance')

    properties = Property.objects.all()
    for property in properties:
        root = AccessLevelInstance.objects.get(organization=property.organization, depth=1)
        property.access_level_instance = root
        property.save()


@transaction.atomic
def assign_taxlots_to_root_acces_level(apps, schema_editor):
    TaxLot = apps.get_model('seed', 'TaxLot')
    AccessLevelInstance = apps.get_model('orgs', 'AccessLevelInstance')

    taxlots = TaxLot.objects.all()
    for taxlot in taxlots:
        root = AccessLevelInstance.objects.get(organization=taxlot.organization, depth=1)
        taxlot.access_level_instance = root
        taxlot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0028_auto_20230413_1250'),
        ('seed', '0203_column_unique_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='access_level_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='orgs.accesslevelinstance'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='access_level_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxlots', to='orgs.accesslevelinstance'),
        ),
        migrations.RunPython(assign_properties_to_root_acces_level, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(assign_taxlots_to_root_acces_level, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='property',
            name='access_level_instance',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='orgs.accesslevelinstance'),
        ),
        migrations.AlterField(
            model_name='taxlot',
            name='access_level_instance',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='taxlots', to='orgs.accesslevelinstance'),
        ),        
    ]
