# Generated by Django 3.2.20 on 2023-09-08 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0205_auto_20230913_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atevent",
            name="building_file",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.buildingfile"),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="event",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="scenarios", to="seed.atevent"),
        ),
    ]
