# Generated by Django 3.2.20 on 2023-09-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0207_uniformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='seed.atevent'),
        ),
    ]
