# Generated by Django 3.2.18 on 2023-06-23 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_auto_20230413_1250'),
        ('seed', '0210_auto_add_props_to_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='raw_access_level_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.accesslevelinstance'),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='raw_access_level_instance_error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='raw_access_level_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.accesslevelinstance'),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='raw_access_level_instance_error',
            field=models.TextField(null=True),
        ),
    ]
