# Generated by Django 3.2.23 on 2024-01-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0210_natural_sort'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='derivedcolumn',
            name='unique_name_for_organization',
        ),
        migrations.AddConstraint(
            model_name='derivedcolumn',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'inventory_type'), name='unique_name_for_organization'),
        ),
    ]
