# Generated by Django 3.2.23 on 2024-01-05 21:06

import timescale.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0210_natural_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='7 days'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('data_logger', 'column_name'), ('data_logger', 'display_name')},
        ),
    ]
