# Generated by Django 3.2.18 on 2023-12-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0213_move_filtergroup_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtergroup',
            name='label_logic',
        ),
        migrations.RemoveField(
            model_name='filtergroup',
            name='labels',
        ),
    ]
