# Generated by Django 3.2.23 on 2024-02-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0213_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, choices=[(1, 'Is this a new construction or acquisition?'), (2, 'Do you have data to report?'), (3, 'Is this value correct?'), (4, 'Are these values correct?'), (5, 'Other or multiple flags; explain in Additional Notes field')], max_length=1024, null=True)),
                ('resolution', models.CharField(blank=True, max_length=1024, null=True)),
                ('passed_checks', models.BooleanField(default=False)),
                ('new_or_acquired', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.goal')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.property')),
            ],
        ),
    ]
