# Generated by Django 3.2.23 on 2024-03-11 23:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('seed', '0215_accountability_hierarchy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('data_logger', 'display_name'), ('data_logger', 'column_name')},
        ),
    ]
