# Generated by Django 3.2.16 on 2022-12-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0215_accountability_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='derived_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxlotstate',
            name='derived_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
