# Generated by Django 3.2.25 on 2024-05-07 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0216_alter_sensor_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="commitment_sqft",
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
