# Generated by Django 3.2.23 on 2024-03-13 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0031_org_audit_template_fields"),
        ("seed", "0216_alter_sensor_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTemplateConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "update_at_day",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)],
                    ),
                ),
                (
                    "update_at_hour",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)],
                    ),
                ),
                (
                    "update_at_minute",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)],
                    ),
                ),
                ("last_update_date", models.DateTimeField(blank=True, null=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orgs.organization")),
            ],
        ),
    ]
