# Generated by Django 3.2.25 on 2024-03-20 19:40

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0031_encrypt_existing_audit_template_passwords"),
        ("seed", "0216_alter_sensor_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("element_id", models.CharField(db_index=True, max_length=36, null=True)),
                ("description", models.TextField(db_collation="natural_sort", null=True)),
                ("installation_date", models.DateField(db_index=True, null=True)),
                (
                    "condition_index",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)],
                    ),
                ),
                ("remaining_service_life", models.FloatField(null=True)),
                ("replacement_cost", models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ("manufacturing_date", models.DateField(null=True)),
                ("extra_data", models.JSONField(default=dict)),
                ("code", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="elements", to="seed.uniformat")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.organization")),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="elements", to="seed.property")),
            ],
            options={
                "ordering": ["-installation_date", "description"],
            },
        ),
        migrations.AddIndex(
            model_name="element",
            index=django.contrib.postgres.indexes.GinIndex(fields=["extra_data"], name="extra_data_gin_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="element",
            unique_together={("organization", "element_id")},
        ),
    ]
