# Generated by Django 3.2.23 on 2024-02-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0216_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, choices=[('Is this a new construction or acquisition?', 'Is this a new construction or acquisition?'), ('Do you have data to report?', 'Do you have data to report?'), ('Is this value correct?', 'Is this value correct?'), ('Are these values correct?', 'Are these values correct?'), ('Other or multiple flags; explain in Additional Notes field', 'Other or multiple flags; explain in Additional Notes field')], max_length=1024, null=True)),
                ('resolution', models.CharField(blank=True, max_length=1024, null=True)),
                ('passed_checks', models.BooleanField(default=False)),
                ('new_or_acquired', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.goal')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.property')),
            ],
        ),
    ]
