# Generated by Django 3.2.23 on 2024-02-12 20:27

import django.db.models.deletion
from django.db import migrations, models, transaction


@transaction.atomic
def backfill_historical_notes(apps, schema_editor):
    Property = apps.get_model("seed", "Property")
    HistoricalNote = apps.get_model("seed", "HistoricalNote")

    properties_to_update = Property.objects.filter(historical_note__isnull=True)

    historical_notes_to_create = [
        HistoricalNote(property=property, text='')
        for property in properties_to_update
    ]
    HistoricalNote.objects.bulk_create(historical_notes_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0217_goalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historical_note', to='seed.property')),
            ],
        ),
        migrations.RunPython(backfill_historical_notes)
    ]
