# Generated by Django 3.2.25 on 2024-07-09 21:47

from django.db import migrations
import quantityfield.fields
from seed.utils.organizations import default_pm_mappings


def forwards(apps, schema_editor):
    Column = apps.get_model("seed", "Column")
    Organization = apps.get_model("orgs", "Organization")
    
    new_columns = [
        {
            "column_name": "water_use",
            "table_name": "PropertyState",
            "display_name": "Water Use",
            "column_description": "Water Use",
            "data_type": "water_use",
        },
        {
            "column_name": "indoor_water_use",
            "table_name": "PropertyState",
            "display_name": "Indoor Water Use",
            "column_description": "Indoor Water Use (All Water Sources)",
            "data_type": "water_use",
        },
        {
            "column_name": "outdoor_water_use",
            "table_name": "PropertyState",
            "display_name": "Outdoor Water Use",
            "column_description": "Outdoor Water Use (All Water Sources)",
            "data_type": "water_use",
        },
        {
            "column_name": "wui",
            "table_name": "PropertyState",
            "display_name": "WUI",
            "column_description": "Water Use Intensity",
            "data_type": "wui",
        },
        {
            "column_name": "indoor_wui",
            "table_name": "PropertyState",
            "display_name": "Indoor WUI",
            "column_description": "Indoor Water Use Intensity",
            "data_type": "wui",
        },
    ]

    for org in Organization.objects.all():
        # create new columns
        for column in new_columns:
            Column.objects.create(**{**column, "organization_id": org.id})

        # update existing default profile mappings
        default_profile = org.columnmappingprofile_set.filter(profile_type=0).first()
        if not default_profile:
            continue

        for mapping in default_pm_mappings():
            if mapping not in default_profile.mappings:
                default_profile.mappings.append(mapping)

        default_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0217_goal_commitment_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='indoor_water_use',
            field=quantityfield.fields.QuantityField(base_units='kgal', blank=True, null=True, unit_choices=['kgal']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='indoor_wui',
            field=quantityfield.fields.QuantityField(base_units='gal/ft**2/year', blank=True, null=True, unit_choices=['gal/ft**2/year']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='outdoor_water_use',
            field=quantityfield.fields.QuantityField(base_units='kgal', blank=True, null=True, unit_choices=['kgal']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='water_use',
            field=quantityfield.fields.QuantityField(base_units='kgal', blank=True, null=True, unit_choices=['kgal']),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='wui',
            field=quantityfield.fields.QuantityField(base_units='gal/ft**2/year', blank=True, null=True, unit_choices=['gal/ft**2/year']),
        ),
        migrations.RunPython(forwards)
    ]
