# Generated by Django 3.2.25 on 2024-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0217_goal_commitment_sqft"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="is_option_for_reports_x_axis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="column",
            name="is_option_for_reports_y_axis",
            field=models.BooleanField(default=False),
        ),
    ]
