# Generated by Django 3.2.20 on 2023-10-24 21:54

import django.db.models.deletion
import quantityfield.fields
from django.db import migrations, models


def forwards(apps, schema_editor):
    Column = apps.get_model("seed", "Column")
    Organization = apps.get_model("orgs", "Organization")
    Label = apps.get_model("seed", "StatusLabel")

    wui_column = {
        "column_name": "site_wui",
        "table_name": "PropertyState",
        "display_name": "Site WUI",
        "column_description": "Site WUI",
        "data_type": "wui",
    }

    # Add to all organizations
    for org_id in list(Organization.objects.values_list("id", flat=True)):
        Column.objects.create(**{**wui_column, "organization_id": org_id})

    # Populate the default labels for goal rules.
    NEW_DEFAULT_LABELS = [
        "High EUI % Change",
        "Low EUI % Change",
        "High WUI",
        "Low WUI" "High WUI % Change",
        "Low WUI % Change",
        "High Area",
        "Low Area",
        "High Area % Change",
        "Low Area % Change",
    ]

    for org in Organization.objects.all():
        for label in NEW_DEFAULT_LABELS:
            Label.objects.get_or_create(name=label, super_organization=org, defaults={"color": "blue"}, show_in_list=True)


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0217_goal_commitment_sqft"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertystate",
            name="site_wui",
            field=quantityfield.fields.QuantityField(base_units="gal/ft**2/year", blank=True, null=True, unit_choices=["gal/ft**2/year"]),
        ),
        migrations.AlterField(
            model_name="rule",
            name="data_type",
            field=models.IntegerField(
                choices=[(0, "number"), (1, "string"), (2, "date"), (3, "year"), (4, "area"), (5, "eui"), (6, "wui")], null=True
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE seed_propertyview_labels RENAME TO seed_propertyviewlabel",
                    reverse_sql="ALTER TABLE seed_propertyviewlabel RENAME TO seed_propertyview_labels",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PropertyViewLabel",
                    fields=[
                        ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("propertyview", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.propertyview")),
                        ("statuslabel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.statuslabel")),
                    ],
                ),
                migrations.AlterField(
                    model_name="propertyview",
                    name="labels",
                    field=models.ManyToManyField(through="seed.PropertyViewLabel", to="seed.StatusLabel"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="propertyviewlabel",
            name="goal",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="seed.goal"),
        ),
        migrations.AlterField(
            model_name="rule",
            name="field",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="cross_cycle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="propertyviewlabel",
            constraint=models.UniqueConstraint(fields=("propertyview", "statuslabel", "goal"), name="unique_propertyview_statuslabel_goal"),
        ),
        migrations.RunPython(forwards),
    ]
