# Generated by Django 3.2.25 on 2024-07-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0218_auto_20240604_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="service",
            field=models.IntegerField(choices=[(1, "BSyncr"), (2, "BETTER"), (3, "EUI"), (4, "CO2"), (5, "EEEJ"), (6, "Hannah")]),
        ),
    ]
