# Generated by Django 3.2.20 on 2023-10-24 21:54

import django.db.models.deletion
from django.db import connection, migrations, models


def forwards(apps, schema_editor):
    Organization = apps.get_model("orgs", "Organization")
    Label = apps.get_model("seed", "StatusLabel")

    # Populate the default labels for goal rules.
    NEW_DEFAULT_LABELS = [
        "High EUI % Change",
        "Low EUI % Change",
        "High Area",
        "Low Area",
        "High Area % Change",
        "Low Area % Change",
    ]

    for org in Organization.objects.all():
        for label in NEW_DEFAULT_LABELS:
            Label.objects.get_or_create(name=label, super_organization=org, defaults={"color": "blue"})


def remove_unique_constraint(apps, schema_editor):
    # The auto generated unique constraint for PropertyViewLabels is PropertyView_id and StatusLabel_id.
    # The constraint needs to be updated to include PropertyView_id, StatusLabel_id, and Goal.id
    PropertyViewLabel = apps.get_model("seed", "PropertyViewLabel")
    table_name = PropertyViewLabel._meta.db_table

    # Get the original unique constraint
    constraints = connection.introspection.get_constraints(connection.cursor(), table_name)
    constraint_names = [
        name
        for name, details in constraints.items()
        if details.get("unique") and set(details.get("columns")) == {"propertyview_id", "statuslabel_id"}
    ]
    # Remove the constraint
    if constraint_names:
        with connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE {table_name} DROP CONSTRAINT {constraint_names[0]};")
    # A new unique constraint will be created in the following operation


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0219_auto_20240604_1605"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE seed_propertyview_labels RENAME TO seed_propertyviewlabel",
                    reverse_sql="ALTER TABLE seed_propertyviewlabel RENAME TO seed_propertyview_labels",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PropertyViewLabel",
                    fields=[
                        ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("propertyview", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.propertyview")),
                        ("statuslabel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.statuslabel")),
                    ],
                ),
                migrations.AlterField(
                    model_name="propertyview",
                    name="labels",
                    field=models.ManyToManyField(through="seed.PropertyViewLabel", to="seed.StatusLabel"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="propertyviewlabel",
            name="goal",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="seed.goal"),
        ),
        migrations.AlterField(
            model_name="rule",
            name="field",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="cross_cycle",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(remove_unique_constraint),
        migrations.AddConstraint(
            model_name="propertyviewlabel",
            constraint=models.UniqueConstraint(fields=("propertyview", "statuslabel", "goal"), name="unique_propertyview_statuslabel_goal"),
        ),
        migrations.RunPython(forwards),
    ]
