# Generated by Django 3.2.25 on 2024-06-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0222_cross_cycle_data_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="is_excluded_from_hash",
            field=models.BooleanField(default=False),
        ),
    ]
