# Generated by Django 3.2.25 on 2024-07-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0224_alter_meter_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="service",
            field=models.IntegerField(
                choices=[
                    (1, "BSyncr"),
                    (2, "BETTER"),
                    (3, "EUI"),
                    (4, "CO2"),
                    (5, "EEEJ"),
                    (6, "Element Statistics"),
                    (7, "armys_prioritization_pathway"),
                ]
            ),
        ),
    ]
