# Generated by Django 3.2.25 on 2024-09-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0228_alter_analysis_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cycle",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.cycle"),
        ),
    ]
