
# Generated by Django 3.2.25 on 2024-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0230_add_extra_data_to_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="is_updating",
            field=models.BooleanField(default=False),
        ),
    ]
