# Generated by Django 3.2.25 on 2024-09-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0230_inventorygroup_inventorygroupmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygroupmapping',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='seed.property'),
        ),
        migrations.AlterField(
            model_name='inventorygroupmapping',
            name='taxlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='seed.taxlot'),
        ),
    ]
