# Generated by Django 3.2.25 on 2024-08-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0033_organization_public_geojson_enabled"),
        ("seed", "0231_column_is_updating"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("inventory_type", models.IntegerField(choices=[(0, "Property"), (1, "Tax Lot")], default=0)),
                (
                    "access_level_instance",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="groups", to="orgs.accesslevelinstance"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="groups", to="orgs.organization"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryGroupMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="seed.inventorygroup")),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="seed.property")),
                ("taxlot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="seed.taxlot")),
            ],
        ),
        migrations.AlterField(
            model_name="inventorygroupmapping",
            name="property",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="group_mappings", to="seed.property"
            ),
        ),
        migrations.AlterField(
            model_name="inventorygroupmapping",
            name="taxlot",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="group_mappings", to="seed.taxlot"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorygroup",
            constraint=models.UniqueConstraint(fields=("name", "organization"), name="unique_group_name_for_organization"),
        ),
    ]
