# Generated by Django 3.2.25 on 2024-11-01 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0232_reportconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["name"]},
        ),
    ]
