# Generated by Django 3.2.25 on 2024-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0232_reportconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='incoming_property_labels',
            field=models.TextField(blank=True, null=True),
        ),
    ]
