# Generated by Django 3.2.25 on 2024-11-21 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Goal = apps.get_model("seed", "Goal")
    Goal.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seed', '0233_alter_goal_options'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AlterModelOptions(
            name='goal',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='access_level_instance',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='area_column',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='baseline_cycle',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='commitment_sqft',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current_cycle',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='eui_column1',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='eui_column2',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='eui_column3',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_percentage',
        ),
        migrations.AddField(
            model_name='goal',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_seed.goal_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('standard', 'standard'), ('transaction', 'transaction'), ('multifamily', 'multifamily'), ('water_treatment', 'water_treatment'), ('data_center', 'data_center')], default='standard', max_length=50)),
                ('commitment_sqft', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('access_level_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.accesslevelinstance')),
                ('baseline_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_baseline_cycles', to='seed.cycle')),
                ('current_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_current_cycles', to='seed.cycle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('goal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seed.goal')),
                ('name', models.CharField(max_length=255)),
                ('area_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_area_columns', to='seed.column')),
                ('data_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.datareport')),
                ('eui_column1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_eui_column1s', to='seed.column')),
                ('eui_column2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_eui_column2s', to='seed.column')),
                ('eui_column3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_eui_column3s', to='seed.column')),
                ('transaction_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_transaction_columns', to='seed.column')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('seed.goal',),
        ),
        migrations.CreateModel(
            name='GoalStandard',
            fields=[
                ('goal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seed.goal')),
                ('name', models.CharField(max_length=255)),
                ('area_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_area_columns', to='seed.column')),
                ('data_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.datareport')),
                ('eui_column1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_eui_column1s', to='seed.column')),
                ('eui_column2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_eui_column2s', to='seed.column')),
                ('eui_column3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_eui_column3s', to='seed.column')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('seed.goal',),
        ),
    ]
