# Generated by Django 3.2.25 on 2024-12-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0234_transaction_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertystate",
            name="incoming_labels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxlotstate",
            name="incoming_labels",
            field=models.TextField(blank=True, null=True),
        ),
    ]
