# Generated by Django 3.2.25 on 2024-10-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0235_inventorygroup_inventorygroupmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="systems", to="seed.inventorygroup")),
            ],
        ),
        migrations.CreateModel(
            name="BatterySystem",
            fields=[
                (
                    "system_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="seed.system",
                    ),
                ),
                ("efficiency", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("voltage", models.IntegerField()),
            ],
            bases=("seed.system",),
        ),
        migrations.CreateModel(
            name="DESSystem",
            fields=[
                (
                    "system_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="seed.system",
                    ),
                ),
                ("type", models.IntegerField(choices=[(0, "Boiler"), (1, "Chiller"), (2, "CHP")])),
                ("capacity", models.IntegerField()),
                ("count", models.IntegerField(default=1)),
            ],
            bases=("seed.system",),
        ),
        migrations.CreateModel(
            name="EVSESystem",
            fields=[
                (
                    "system_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="seed.system",
                    ),
                ),
                ("type", models.IntegerField(choices=[(0, "Level1-120V"), (1, "Level2-240V"), (2, "Level3-DC Fast")])),
                ("power", models.IntegerField()),
                ("count", models.IntegerField(default=1)),
            ],
            bases=("seed.system",),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("emission_factor", models.IntegerField(null=True)),
                ("system", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="services", to="seed.system")),
            ],
        ),
        migrations.AddConstraint(
            model_name="system",
            constraint=models.UniqueConstraint(fields=("group", "name"), name="unique_name_for_group"),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(fields=("system", "name"), name="unique_name_for_system"),
        ),
    ]
