# Generated by Django 3.2.25 on 2024-10-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0236_auto_20241008_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="system",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="meters", to="seed.system"
            ),
        ),
    ]
