# Generated by Django 3.2.25 on 2024-10-30 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0237_meter_systems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="system",
            options={"ordering": ["name"]},
        ),
    ]
