# Generated by Django 3.2.25 on 2024-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0240_auto_20241106_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Coal (anthracite)"),
                    (2, "Coal (bituminous)"),
                    (3, "Coke"),
                    (4, "Diesel"),
                    (25, "District Chilled Water"),
                    (5, "District Chilled Water - Absorption"),
                    (6, "District Chilled Water - Electric"),
                    (7, "District Chilled Water - Engine"),
                    (8, "District Chilled Water - Other"),
                    (9, "District Hot Water"),
                    (10, "District Steam"),
                    (26, "Electric"),
                    (11, "Electric - Grid"),
                    (12, "Electric - Solar"),
                    (13, "Electric - Wind"),
                    (14, "Fuel Oil (No. 1)"),
                    (15, "Fuel Oil (No. 2)"),
                    (16, "Fuel Oil (No. 4)"),
                    (17, "Fuel Oil (No. 5 and No. 6)"),
                    (18, "Kerosene"),
                    (19, "Natural Gas"),
                    (20, "Other:"),
                    (21, "Propane"),
                    (22, "Wood"),
                    (23, "Cost"),
                    (24, "Electric - Unknown"),
                    (99, "Custom Meter"),
                    (27, "Potable Indoor"),
                    (29, "Potable Outdoor"),
                    (28, "Potable: Mixed Indoor/Outdoor"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
