# Generated by Django 3.2.25 on 2025-04-07 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0041_add_at_tracking_fields"),
        ("seed", "0242_add_meter_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitiesPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "energy_running_sum_percentage",
                    models.FloatField(
                        default=0.75,
                        validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)],
                    ),
                ),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.organization")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="facilitiesplan",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="unique_name_for_plan"),
        ),
    ]
