# Generated by Django 3.2.25 on 2025-04-08 22:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0041_add_at_tracking_fields"),
        ("seed", "0242_add_meter_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitiesPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "energy_running_sum_percentage",
                    models.FloatField(
                        default=0.75,
                        validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)],
                    ),
                ),
                (
                    "building_category_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "compliance_cycle_year_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "electric_data_source_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "electric_energy_usage_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "electric_eui_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "exclude_from_plan_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "gas_data_source_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "gas_energy_usage_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "gas_eui_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "gross_floor_area_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "include_in_total_denominator_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.organization")),
                (
                    "require_in_plan_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "steam_energy_usage_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "steam_eui_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "total_eui_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="facilitiesplan",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="unique_name_for_plan"),
        ),
    ]
