# Generated by Django 3.2.25 on 2025-02-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0041_add_at_tracking_fields'),
        ('seed', '0242_add_meter_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gfa_units', models.CharField(choices=[('ft2', 'ft2'), ('m2', ',2')], default='ft2', max_length=20)),
                ('electricity_units', models.CharField(choices=[('GJ', 'GJ'), ('kBtu', 'kBtu'), ('kWh', 'kWh'), ('MBtu/MMBtu', 'MBtu/MMBtu'), ('MWh', 'MWh')], default=None, max_length=50)),
                ('natural_gas_units', models.CharField(choices=[('GJ', 'GJ'), ('kBtu', 'kBtu'), ('MBtu/MMBtu', 'MBtu/MMBtu'), ('therms', 'therms'), ('kWh', 'kWh'), ('kcf', 'kcf'), ('Mcf', 'Mcf')], default=None, max_length=50)),
                ('electricity_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_column', to='seed.column')),
                ('gfa_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gfa_column', to='seed.column')),
                ('natural_gas_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natural_gas_column', to='seed.column')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
    ]
