# Generated by Django 3.2.25 on 2025-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0243_update_bsync_measures_v2_6_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="unique_goal_name_per_organization"),
        ),
    ]
