# Generated by Django 3.2.25 on 2025-08-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0042_organizationuser_settings'),
        ('seed', '0243_update_bsync_measures_v2_6_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_cycle',
        ),
        migrations.AddField(
            model_name='goal',
            name='salesforce_goal_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='salesforce_goal_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='salesforce_partner_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='salesforce_partner_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CycleGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_annual_report_id', models.CharField(max_length=255, null=True)),
                ('salesforce_annual_report_name', models.CharField(max_length=255, null=True)),
                ('current_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='seed.cycle')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_cycles', to='seed.goal')),
            ],
        ),
        migrations.CreateModel(
            name='BBSalesforceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_url', models.CharField(blank=True, max_length=128, null=True)),
                ('client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bb_salesforce_config', to='orgs.organization')),
            ],
        ),
    ]
