# Generated by Django 3.2.25 on 2025-06-24 18:35

import django.db.models.deletion
from django.db import migrations, models, transaction


@transaction.atomic
def create_cyclegoal_for_each_goal_and_attach_notes(apps, schema_editor):
    Goal = apps.get_model("seed", "Goal")
    GoalNote = apps.get_model("seed", "GoalNote")
    CycleGoal = apps.get_model("seed", "CycleGoal")

    # for each goal
    for goal in Goal.objects.all().iterator():
        # create a cycle goal
        cycle_goal = CycleGoal.objects.create(goal=goal, current_cycle=goal.current_cycle)

        # add cycle goal to all the goal notes
        GoalNote.objects.filter(goal=goal).update(cycle_goal=cycle_goal)


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0243_update_bsync_measures_v2_6_0"),
    ]

    operations = [
        migrations.CreateModel(
            name="CycleGoal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_cycle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goals", to="seed.cycle")),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="current_cycles", to="seed.goal")),
            ],
        ),
        migrations.AddField(
            model_name="goalnote",
            name="cycle_goal",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="seed.cyclegoal"),
        ),
        migrations.RunPython(
            code=create_cyclegoal_for_each_goal_and_attach_notes,
        ),
        migrations.AlterField(
            model_name="goalnote",
            name="cycle_goal",
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to="seed.cyclegoal"),
        ),
        migrations.RemoveField(
            model_name="goal",
            name="current_cycle",
        ),
        migrations.RemoveField(
            model_name="goalnote",
            name="goal",
        ),
    ]
