# Generated by Django 3.2.25 on 2025-06-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0243_update_bsync_measures_v2_6_0"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="current_cycle",
        ),
        migrations.CreateModel(
            name="CycleGoal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_cycle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goals", to="seed.cycle")),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="current_cycles", to="seed.goal")),
            ],
        ),
    ]
