# Generated by Django 3.2.25 on 2025-04-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0041_add_at_tracking_fields"),
        ("seed", "0243_auto_20250408_1553"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitiesPlanRun",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ali", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.accesslevelinstance")),
                ("cycle", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="seed.cycle")),
                (
                    "facilities_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="seed.facilitiesplan"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilitiesPlanRunProperty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rank", models.IntegerField()),
                ("running_percentage", models.FloatField()),
                ("running_square_footage", models.FloatField()),
                (
                    "run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_rankings",
                        to="seed.facilitiesplanrun",
                    ),
                ),
                ("view", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="seed.propertyview")),
            ],
        ),
    ]
