# Generated by Django 3.2.25 on 2025-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0244_facilitiesplanrun_facilitiesplanrunproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitiesplanrunproperty",
            name="percentage_of_total_energy_usage",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilitiesplanrunproperty",
            name="total_energy_usage",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
