# Generated by Django 3.2.25 on 2025-06-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0244_auto_20250613_1235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalnote",
            name="goal",
        ),
        migrations.AddField(
            model_name="goalnote",
            name="cycle_goal",
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to="seed.cyclegoal"),
            preserve_default=False,
        ),
    ]
