# Generated by Django 3.2.25 on 2025-07-29 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0042_organizationuser_settings"),
        ("seed", "0244_auto_20250624_1135"),
    ]

    operations = [
        migrations.CreateModel(
            name="BBSalesforceConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salesforce_url", models.CharField(blank=True, max_length=128, null=True)),
                ("client_id", models.CharField(blank=True, max_length=128, null=True)),
                ("client_secret", models.CharField(blank=True, max_length=128, null=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orgs.organization")),
            ],
        ),
    ]
