# Generated by Django 3.2.25 on 2025-06-25 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0042_organizationuser_settings"),
        ("seed", "0244_goal_name_unique_within_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitiesPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "energy_running_sum_percentage",
                    models.FloatField(
                        default=0.75,
                        validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)],
                    ),
                ),
                (
                    "compliance_cycle_year_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "electric_energy_usage_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "exclude_from_plan_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "gas_energy_usage_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "include_in_total_denominator_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.organization")),
                (
                    "require_in_plan_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
                (
                    "steam_energy_usage_column",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="seed.column"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FacilitiesPlanRun",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("ali", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.accesslevelinstance")),
                ("cycle", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="seed.cycle")),
                ("display_columns", models.ManyToManyField(to="seed.Column")),
                (
                    "facilities_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="seed.facilitiesplan"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilitiesPlanRunProperty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_energy_usage", models.FloatField()),
                ("percentage_of_total_energy_usage", models.FloatField()),
                ("rank", models.IntegerField()),
                ("running_percentage", models.FloatField()),
                ("running_square_footage", models.FloatField()),
                (
                    "run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_rankings",
                        to="seed.facilitiesplanrun",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="facility_plan_runs", to="seed.propertyview"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="facilitiesplan",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="unique_name_for_plan"),
        ),
    ]
