# Generated by Django 3.2.25 on 2025-09-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0244_auto_20250805_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="partner_note",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
