# Generated by Django 3.2.25 on 2025-04-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0245_auto_20250411_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitiesplanrunproperty",
            name="view",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="facility_plan_runs", to="seed.propertyview"
            ),
        ),
    ]
