# Generated by Django 3.2.25 on 2025-09-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0245_goal_partner_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="partner_note",
            field=models.TextField(default=""),
        ),
    ]
