# Generated by Django 3.2.25 on 2025-08-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0042_organizationuser_settings"),
        ("seed", "0245_bbsalesforceconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="salesforce_goal_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_goal_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_partner_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_partner_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bbsalesforceconfig",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="bb_salesforce_config", to="orgs.organization"
            ),
        ),
    ]
