# Generated by Django 4.2.23 on 2025-06-30 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0245_facilities_plan"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="note",
            new_name="seed_note_organiz_909e1a_idx",
            old_fields=("organization", "note_type"),
        ),
        migrations.RenameIndex(
            model_name="propertyauditlog",
            new_name="seed_proper_state_i_9c4415_idx",
            old_fields=("state", "name"),
        ),
        migrations.RenameIndex(
            model_name="propertyauditlog",
            new_name="seed_proper_parent__8a8a20_idx",
            old_fields=("parent_state1", "parent_state2"),
        ),
        migrations.RenameIndex(
            model_name="propertymeasure",
            new_name="seed_proper_propert_3e8b15_idx",
            old_fields=("property_measure_name", "property_state"),
        ),
        migrations.RenameIndex(
            model_name="propertystate",
            new_name="seed_proper_hash_ob_6497e4_idx",
            old_fields=("hash_object",),
        ),
        migrations.RenameIndex(
            model_name="propertystate",
            new_name="seed_proper_import__302589_idx",
            old_fields=("import_file", "data_state"),
        ),
        migrations.RenameIndex(
            model_name="propertystate",
            new_name="seed_proper_import__a13e5f_idx",
            old_fields=("import_file", "data_state", "merge_state"),
        ),
        migrations.RenameIndex(
            model_name="propertystate",
            new_name="seed_proper_import__ddad37_idx",
            old_fields=("import_file", "data_state", "source_type"),
        ),
        migrations.RenameIndex(
            model_name="propertyview",
            new_name="seed_proper_state_i_dae98d_idx",
            old_fields=("state", "cycle"),
        ),
        migrations.RenameIndex(
            model_name="taxlotauditlog",
            new_name="seed_taxlot_state_i_093659_idx",
            old_fields=("state", "name"),
        ),
        migrations.RenameIndex(
            model_name="taxlotauditlog",
            new_name="seed_taxlot_parent__a3e767_idx",
            old_fields=("parent_state1", "parent_state2"),
        ),
        migrations.RenameIndex(
            model_name="taxlotproperty",
            new_name="seed_taxlot_cycle_i_577466_idx",
            old_fields=("cycle", "property_view"),
        ),
        migrations.RenameIndex(
            model_name="taxlotproperty",
            new_name="seed_taxlot_cycle_i_b3c514_idx",
            old_fields=("cycle", "taxlot_view"),
        ),
        migrations.RenameIndex(
            model_name="taxlotproperty",
            new_name="seed_taxlot_propert_be033b_idx",
            old_fields=("property_view", "taxlot_view"),
        ),
        migrations.RenameIndex(
            model_name="taxlotstate",
            new_name="seed_taxlot_hash_ob_6c9805_idx",
            old_fields=("hash_object",),
        ),
        migrations.RenameIndex(
            model_name="taxlotstate",
            new_name="seed_taxlot_import__8f600b_idx",
            old_fields=("import_file", "data_state"),
        ),
        migrations.RenameIndex(
            model_name="taxlotstate",
            new_name="seed_taxlot_import__bc9aae_idx",
            old_fields=("import_file", "data_state", "merge_state"),
        ),
        migrations.RenameIndex(
            model_name="taxlotview",
            new_name="seed_taxlot_state_i_aaa042_idx",
            old_fields=("state", "cycle"),
        ),
    ]
