# Generated by Django 3.2.25 on 2025-08-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0246_auto_20250804_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclegoal",
            name="salesforce_annual_report_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cyclegoal",
            name="salesforce_annual_report_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
