# Generated by Django 3.2.25 on 2025-04-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0246_alter_facilitiesplanrunproperty_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitiesplanrun",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facilitiesplanrun",
            name="run_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
