# Generated by Django 4.2.24 on 2025-09-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0246_rename_indices"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateMeterSystem",
            fields=[
                (
                    "system_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="seed.system",
                    ),
                ),
            ],
            bases=("seed.system",),
        ),
    ]
