# Generated by Django 3.2.25 on 2025-09-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0246_auto_20250903_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
