# Generated by Django 3.2.25 on 2025-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0247_goal_partner_note_approval_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="partner_note",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
