# Generated by Django 3.2.25 on 2025-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0247_auto_20250429_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitiesplanrun",
            name="run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
