# Generated by Django 4.2.24 on 2025-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0247_aggregatemetersystem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="service",
            field=models.IntegerField(
                choices=[
                    (1, "BSyncr"),
                    (2, "BETTER"),
                    (3, "EUI"),
                    (4, "CO2"),
                    (5, "EEEJ"),
                    (6, "Element Statistics"),
                    (7, "Building Upgrade Recommendation"),
                    (8, "HVAC Metrics"),
                ]
            ),
        ),
    ]
