# Generated by Django 3.2.25 on 2025-10-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0043_add_bb_salesforce_enabled"),
        ("seed", "0248_alter_goal_partner_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.organizationuser"),
        ),
    ]
