# Generated by Django 3.2.25 on 2025-04-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0248_alter_facilitiesplanrun_run_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitiesplanrun",
            name="columns",
            field=models.ManyToManyField(to="seed.Column"),
        ),
    ]
