# Generated by Django 4.2.24 on 2025-10-23 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0044_add_bb_salesforce_enabled"),
        ("seed", "0249_alter_analysis_service"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'orgs_organization'::regclass
                      AND contype = 'p'
                ) THEN
                    ALTER TABLE orgs_organization
                    ADD CONSTRAINT orgs_organization_pkey PRIMARY KEY (id);
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'orgs_organizationuser'::regclass
                      AND contype = 'p'
                ) THEN
                    ALTER TABLE orgs_organizationuser
                    ADD CONSTRAINT orgs_organizationuser_pkey PRIMARY KEY (id);
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'orgs_organizationuser'::regclass
                      AND conname = 'unique_user_for_organization'
                ) THEN
                    ALTER TABLE orgs_organizationuser
                    ADD CONSTRAINT unique_user_for_organization UNIQUE (user_id, organization_id);
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'seed_cycle'::regclass
                      AND contype = 'p'
                ) THEN
                    ALTER TABLE seed_cycle
                    ADD CONSTRAINT seed_cycle_pkey PRIMARY KEY (id);
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'seed_goal'::regclass
                      AND contype = 'p'
                ) THEN
                    ALTER TABLE seed_goal
                    ADD CONSTRAINT seed_goal_pkey PRIMARY KEY (id);
                END IF;
            END;
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="goal",
            name="current_cycle",
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.organizationuser"),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_goal_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_goal_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_partner_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_partner_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CycleGoal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salesforce_annual_report_id", models.CharField(max_length=255, null=True)),
                ("salesforce_annual_report_name", models.CharField(max_length=255, null=True)),
                ("current_cycle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goals", to="seed.cycle")),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="current_cycles", to="seed.goal")),
            ],
        ),
        migrations.CreateModel(
            name="BBSalesforceConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salesforce_url", models.CharField(blank=True, max_length=128, null=True)),
                ("client_id", models.CharField(blank=True, max_length=128, null=True)),
                ("client_secret", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bb_salesforce_config", to="orgs.organization"
                    ),
                ),
            ],
        ),
    ]
