# Generated by Django 3.2.25 on 2025-04-30 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0249_facilitiesplanrun_columns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facilitiesplanrun",
            old_name="columns",
            new_name="display_columns",
        ),
    ]
