# Generated by Django 4.2.24 on 2025-10-23 22:02

import django.db.models.deletion
from django.db import migrations, models

from seed.utils.migrations import add_missing_primary_keys_sql

# Databases restored from some production backups are missing primary keys on the
# tables this migration references. The operations below add foreign keys to
# orgs_organization(user) and seed_cycle/seed_goal, which PostgreSQL rejects when
# the referenced column has no primary key. Repair those keys first (idempotent)
# so this migration can run on databases that have not applied it yet. Databases
# that already applied 0250 are repaired by 0254_repair_missing_primary_keys.
REPAIR_REFERENCED_PRIMARY_KEYS = add_missing_primary_keys_sql(
    "orgs_organization",
    "orgs_organizationuser",
    "seed_cycle",
    "seed_goal",
)


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0044_add_bb_salesforce_enabled"),
        ("seed", "0249_alter_analysis_service"),
    ]

    operations = [
        migrations.RunSQL(
            sql=REPAIR_REFERENCED_PRIMARY_KEYS,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="goal",
            name="current_cycle",
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="partner_note_approval_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.organizationuser"),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_goal_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_goal_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_partner_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="salesforce_partner_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CycleGoal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salesforce_annual_report_id", models.CharField(max_length=255, null=True)),
                ("salesforce_annual_report_name", models.CharField(max_length=255, null=True)),
                ("current_cycle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goals", to="seed.cycle")),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="current_cycles", to="seed.goal")),
            ],
        ),
        migrations.CreateModel(
            name="BBSalesforceConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salesforce_url", models.CharField(blank=True, max_length=128, null=True)),
                ("client_id", models.CharField(blank=True, max_length=128, null=True)),
                ("client_secret", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bb_salesforce_config", to="orgs.organization"
                    ),
                ),
            ],
        ),
    ]
