# Generated by Django 3.2.25 on 2025-04-30 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0250_rename_columns_facilitiesplanrun_display_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="building_category_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="electric_data_source_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="electric_eui_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="gas_data_source_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="gas_eui_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="gross_floor_area_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="steam_eui_column",
        ),
        migrations.RemoveField(
            model_name="facilitiesplan",
            name="total_eui_column",
        ),
    ]
