# Generated by Django 5.2.13 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0251_null_emaildevice_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyview",
            name="labels",
            field=models.ManyToManyField(
                through="seed.PropertyViewLabel",
                through_fields=("propertyview", "statuslabel"),
                to="seed.StatusLabel",
            ),
        ),
    ]
