# Generated by Django 6.0.5 on 2026-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0252_alter_propertyview_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataview',
            name='filter_groups',
            field=models.ManyToManyField(blank=True, to='seed.filtergroup'),
        ),
    ]
