# Generated by Django 6.1.1 on 2026-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0254_repair_missing_primary_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymeasure",
            name="annual_cost_savings",
            field=models.FloatField(null=True),
        ),
    ]
