# Generated by Django 6.1.1 on 2026-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0254_repair_missing_primary_keys"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="columnlistprofilecolumn",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterField(
            model_name="analysis",
            name="service",
            field=models.IntegerField(
                choices=[
                    (1, "BSyncr"),
                    (2, "BETTER"),
                    (3, "EUI"),
                    (4, "CO2"),
                    (5, "EEEJ"),
                    (6, "Element Statistics"),
                    (7, "Building Upgrade Recommendation"),
                    (8, "HVAC Metrics"),
                    (9, "Building Energy Surrogate Models"),
                ]
            ),
        ),
    ]
