# Generated by Django 6.1.1 on 2026-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seed", "0255_propertymeasure_annual_cost_savings"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymeasure",
            name="annual_electricity_savings",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="propertymeasure",
            name="annual_natural_gas_savings",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="propertymeasure",
            name="annual_peak_electricity_reduction",
            field=models.FloatField(null=True),
        ),
    ]
