# Generated by Django 6.1.1 on 2026-10-08 19:59

from django.db import migrations, models
from django.db.models import Count


def validate_inventory_column_names(apps, schema_editor):
    Column = apps.get_model("seed", "Column")
    columns = Column.objects.using(schema_editor.connection.alias)
    duplicate_groups = list(
        columns.exclude(table_name="")
        .filter(organization_id__isnull=False)
        .values("organization_id", "column_name", "table_name")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .order_by("organization_id", "table_name", "column_name")[:10]
    )

    if not duplicate_groups:
        return

    details = []
    for duplicate in duplicate_groups:
        column_ids = list(
            columns.filter(
                organization_id=duplicate["organization_id"],
                column_name=duplicate["column_name"],
                table_name=duplicate["table_name"],
            )
            .order_by("id")
            .values_list("id", flat=True)
        )
        details.append(
            f"organization={duplicate['organization_id']}, table={duplicate['table_name']!r}, "
            f"column={duplicate['column_name']!r}, ids={column_ids}"
        )

    raise RuntimeError("Duplicate inventory Columns must be resolved before applying this migration: " + "; ".join(details))


class Migration(migrations.Migration):
    dependencies = [
        ("data_importer", "0019_accountability_hierarchy"),
        ("orgs", "0046_repair_organizationuser_constraints"),
        ("seed", "0256_propertymeasure_annual_electricity_savings_and_more"),
    ]

    operations = [
        migrations.RunPython(validate_inventory_column_names, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="column",
            name="unique_column_name",
        ),
        migrations.AddConstraint(
            model_name="column",
            constraint=models.UniqueConstraint(
                condition=models.Q(("table_name", "")),
                fields=("organization", "column_name", "is_extra_data"),
                name="unique_raw_column_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="column",
            constraint=models.UniqueConstraint(
                condition=models.Q(("table_name", ""), _negated=True),
                fields=("organization", "column_name", "table_name"),
                name="unique_inventory_column_name",
            ),
        ),
    ]
