---
services:
  appfleet-pipeline:
    image: 991404956194.dkr.ecr.us-west-2.amazonaws.com/nrel-appfleet-pipeline:${APPFLEET_DEPLOY_VERSION:-2.2.0-alpine-e1f2893}
    environment:
      - APPFLEET_TAG_OVERRIDES=${APPFLEET_TAG_OVERRIDES}
      - APPFLEET_RELEASE_NAME=${APPFLEET_RELEASE_NAME:-dev}
      - CONFIG_FILE_URL=${CONFIG_FILE_URL:-https://github.nrel.gov/nrel-cloud-computing/seedcerl-seedweb/raw/main/appfleet-config/appfleet.yml}
      - SLEEP_ONLY=${SLEEP_ONLY:-False}
      - DIFF_ONLY=${DIFF_ONLY:-False}
      - SYNTH_ONLY=${SYNTH_ONLY:-False}
      - LOCAL_CONFIG=${LOCAL_CONFIG}
    volumes:
      - ./.aws:/root/.aws:ro
      - ${PWD}/appfleet-config:/workspace
      - ${PWD}/appfleet-config/appfleet.yml:/workspace/appfleet.yml
