# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0034_merge'),
        ('data_importer', '0004_auto_20160411_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='seed.Cycle'),
        ),
    ]
