# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0005_importfile_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='cycle',
            field=models.ForeignKey(default=370, on_delete=django.db.models.deletion.CASCADE, to='seed.Cycle'),
            preserve_default=False,
        ),
    ]
