# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0007_auto_20161008_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='cached_mapped_columns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
