# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0008_importfile_cached_mapped_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='uploaded_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
