# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0010_importfile_matching_results_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingimportrecord',
            name='building_model_content_type',
        ),
        migrations.RemoveField(
            model_name='buildingimportrecord',
            name='import_record',
        ),
        migrations.RemoveField(
            model_name='datacoercionmapping',
            name='table_column_mapping',
        ),
        migrations.RemoveField(
            model_name='rangevalidationrule',
            name='validationrule_ptr',
        ),
        migrations.RemoveField(
            model_name='validationoutlier',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='table_column_mapping',
        ),
        migrations.DeleteModel(
            name='BuildingImportRecord',
        ),
        migrations.DeleteModel(
            name='DataCoercionMapping',
        ),
        migrations.DeleteModel(
            name='RangeValidationRule',
        ),
        migrations.DeleteModel(
            name='ValidationOutlier',
        ),
        migrations.DeleteModel(
            name='ValidationRule',
        ),
    ]
