# Generated by Django 2.2.10 on 2020-04-28 23:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0012_auto_20181107_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='raw_property_state_to_filename',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
