# Generated by Django 3.0.14 on 2021-07-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0014_importfile_has_generated_headers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importfile',
            options={'ordering': ('-modified', '-created')},
        ),
    ]
