# Generated by Django 3.2.19 on 2023-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0016_auto_20220119_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='multiple_cycle_upload',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
