# Generated by Django 3.2.19 on 2023-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0017_pm_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='multiple_cycle_upload',
            field=models.BooleanField(default=False),
        ),
    ]
