# Generated by Django 3.2.23 on 2024-03-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0030_accountability_hierarchy'),
        ('data_importer', '0018_importfile_multiple_cycle_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecord',
            name='access_level_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='import_record', to='orgs.accesslevelinstance'),
            preserve_default=False,
        ),
    ]
