# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 21:20
from __future__ import unicode_literals

from django.db import migrations
import django_pgjson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='extra_data',
            field=django_pgjson.fields.JsonField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='taxlotstate',
            name='extra_data',
            field=django_pgjson.fields.JsonField(blank=True, default={}),
        ),
    ]
