# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluesky', '0002_auto_20160526_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxlotstate',
            old_name='jurisdiction_taxlot_identifiers',
            new_name='jurisdiction_taxlot_identifier',
        ),
    ]
