# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-02 14:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0004_auto_20160411_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text=b'HTTP response from action'),
        ),
    ]
