# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 17:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0005_auto_20170602_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, db_index=True, help_text='method triggering audit', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_note',
            field=models.TextField(blank=True, help_text='either the note text or a description of the action', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='HTTP response from action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='audit_type',
            field=models.IntegerField(choices=[(0, 'Log'), (1, 'Note')], default=0),
        ),
    ]
