version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - RELEASE_SHA=$(echo $CODEBUILD_SOURCE_VERSION | head -c 7)
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - make IMAGE_REPO_NAME="${IMAGE_REPO_NAME}" NGINX_LISTEN_OPTS="${NGINX_LISTEN_OPTS}" build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - make push
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' > imageDetail.json
artifacts:
  files:
    - imageDetail.json
