#!/usr/bin/env bash

tmp=tmp/angular_locales
dest=seed/static/seed/locales

mkdir -p $tmp

lokalise                \
  --config lokalise.cfg \
    export              \
  --langs fr_CA,en_US   \
  --type json           \
  --include_comments 1  \
  --export_sort a_z     \
  --export_empty base   \
  --dest $tmp

unzip $tmp/SEED_Platform-locale.zip -d $tmp
mv $tmp/locale/fr_CA.json $dest
mv $tmp/locale/en_US.json $dest
rm -rf $tmp
