#!/usr/bin/env bash

# If Lokalise CLI isn't installed, download fr_CA.json and en_US.json files with
# the settings listed below (including comments, sorting from A-Z, and replacing
# empty translations with the base language).

# Then, as shown in the code below, move the unzipped .json files into the
# seed/static/seed/locales directory.

if [[ ! -f lokalise.cfg ]]; then
  echo "Missing lokalise.cfg. Copy from lokalise.cfg.example"
  exit 1
fi

tmp=tmp/angular_locales
dest=seed/static/seed/locales

mkdir -p $tmp

lokalise                \
  --config lokalise.cfg \
    export              \
  --langs fr_CA,en_US   \
  --type json           \
  --include_comments 1  \
  --export_sort a_z     \
  --export_empty base   \
  --dest $tmp

unzip $tmp/SEED_Platform-locale.zip -d $tmp
mv $tmp/locale/fr_CA.json $dest
mv $tmp/locale/en_US.json $dest
rm -rf $tmp
