# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 23:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeduser',
            name='default_building_detail_custom_columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='seeduser',
            name='default_custom_columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
