# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170602_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeduser',
            name='measurement_system',
            field=models.IntegerField(choices=[(0, b'United States customary')], default=0),
        ),
    ]
