# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20181107_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeduser',
            name='is_staff',
        ),
    ]
