# !/usr/bin/env python
# encoding: utf-8
"""
:copyright (c) 2014 - 2018, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Department of Energy) and contributors. All rights reserved.  # NOQA
:author
"""
# TODO: Merge this file with other schema
# https://github.com/SEED-platform/seed/blob/41c104cd105161c949e9cb379aac946ea9202c74/seed/lib/mappings/mapping_data.py  # noqa

# These are fields that are ignored when using methods that automatically determine names and
# cloning records
EXCLUDE_FIELDS = [
    'best_guess_canonical_building',
    'best_guess_confidence',
    'canonical_building',
    'canonical_for_ds',
    'children',
    'confidence',
    'data_state',
    'duplicate',
    'extra_data',
    'id',
    # 'import_file',  # NEED import_file to copy over when we are merging records, leave it in for now.
    'last_modified_by',
    'match_type',
    'merge_state',
    'modified',
    'organization',
    'parents',
    'pk',
    'seed_org',
    'source_type',
    'super_organization',
    # Do not map to the original fields that are no longer quantities
    'source_eui_modeled_orig',
    'site_eui_orig',
    'occupied_floor_area_orig',
    'site_eui_weather_normalized_orig',
    'site_eui_modeled_orig',
    'source_eui_orig',
    'gross_floor_area_orig',
    'conditioned_floor_area_orig',
    'source_eui_weather_normalized_orig',
]

VIEW_COLUMNS_PROPERTY = [
    {
        'name': 'pm_property_id',
        'table': 'PropertyState',
        'displayName': 'PM Property ID',
        'dataType': 'string',
        'pinIfNative': True,
        'dbField': True,
    }, {
        'name': 'pm_parent_property_id',
        'table': 'PropertyState',
        'displayName': 'PM Parent Property ID',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'jurisdiction_tax_lot_id',
        'table': 'TaxLotState',
        'displayName': 'Jurisdiction Tax Lot ID',
        'dataType': 'string',
        'pinIfNative': True,
        'dbField': True,
    }, {
        'name': 'jurisdiction_property_id',
        'table': 'PropertyState',
        'displayName': 'Jurisdiction Property ID',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'ubid',
        'table': 'PropertyState',
        'displayName': 'UBID',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'custom_id_1',
        'table': 'PropertyState',
        'displayName': 'Custom ID 1 (Property)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'custom_id_1',
        'table': 'TaxLotState',
        'displayName': 'Custom ID 1 (Tax Lot)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'address_line_1',
        'table': 'PropertyState',
        'displayName': 'Address Line 1 (Property)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'address_line_1',
        'table': 'TaxLotState',
        'displayName': 'Address Line 1 (Tax Lot)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'address_line_2',
        'table': 'PropertyState',
        'displayName': 'Address Line 2 (Property)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'address_line_2',
        'table': 'TaxLotState',
        'displayName': 'Address Line 2 (Tax Lot)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'city',
        'table': 'PropertyState',
        'displayName': 'City (Property)',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'city',
        'table': 'TaxLotState',
        'displayName': 'City (Tax Lot)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'state',
        'table': 'PropertyState',
        'displayName': 'State (Property)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'state',
        'table': 'TaxLotState',
        'displayName': 'State (Tax Lot)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'postal_code',
        'table': 'PropertyState',
        'displayName': 'Postal Code (Property)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        'name': 'postal_code',
        'table': 'TaxLotState',
        'displayName': 'Postal Code (Tax Lot)',
        'dataType': 'string',
        'duplicateNameInOtherTable': True,
        'dbField': True,
    }, {
        # This field should never be mapped to!
        'name': 'lot_number',
        'table': 'PropertyState',
        'displayName': 'Associated Tax Lot ID',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'property_name',
        'table': 'PropertyState',
        'displayName': 'Property Name',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'latitude',
        'table': 'PropertyState',
        'displayName': 'Latitude',
        'dataType': 'number',
        'dbField': True,
    }, {
        'name': 'longitude',
        'table': 'PropertyState',
        'displayName': 'Longitude',
        'dataType': 'number',
        'dbField': True,
    }, {
        'name': 'campus',
        'table': 'Property',
        'displayName': 'Campus',
        'dataType': 'boolean',
        'type': 'boolean',
        'dbField': True,
    }, {
        'name': 'updated',
        'table': 'Property',
        'displayName': 'Updated (Property)',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
        'duplicateNameInOtherTable': True,
    }, {
        'name': 'created',
        'table': 'Property',
        'displayName': 'Created (Property)',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
        'duplicateNameInOtherTable': True,
    }, {
        'name': 'updated',
        'table': 'TaxLot',
        'displayName': 'Updated (Tax Lot)',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
        'duplicateNameInOtherTable': True,
    }, {
        'name': 'created',
        'table': 'TaxLot',
        'displayName': 'Created (Tax Lot)',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
        'duplicateNameInOtherTable': True,
    }, {
        'name': 'gross_floor_area',
        'table': 'PropertyState',
        'displayName': 'Gross Floor Area',
        'dataType': 'area',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'use_description',
        'table': 'PropertyState',
        'displayName': 'Use Description',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'energy_score',
        'table': 'PropertyState',
        'displayName': 'ENERGY STAR Score',
        'dataType': 'integer',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'property_notes',
        'table': 'PropertyState',
        'displayName': 'Property Notes',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'property_type',
        'table': 'PropertyState',
        'displayName': 'Property Type',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'year_ending',
        'table': 'PropertyState',
        'displayName': 'Year Ending',
        'dataType': 'date',
        'dbField': True,
    }, {
        'name': 'owner',
        'table': 'PropertyState',
        'displayName': 'Owner',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'owner_email',
        'table': 'PropertyState',
        'displayName': 'Owner Email',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'owner_telephone',
        'table': 'PropertyState',
        'displayName': 'Owner Telephone',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'building_count',
        'table': 'PropertyState',
        'displayName': 'Building Count',
        'dataType': 'integer',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'year_built',
        'table': 'PropertyState',
        'displayName': 'Year Built',
        'dataType': 'integer',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'recent_sale_date',
        'table': 'PropertyState',
        'displayName': 'Recent Sale Date',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
    }, {
        'name': 'conditioned_floor_area',
        'table': 'PropertyState',
        'displayName': 'Conditioned Floor Area',
        'dataType': 'area',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'occupied_floor_area',
        'table': 'PropertyState',
        'displayName': 'Occupied Floor Area',
        'dataType': 'area',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'owner_address',
        'table': 'PropertyState',
        'displayName': 'Owner Address',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'owner_city_state',
        'table': 'PropertyState',
        'displayName': 'Owner City/State',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'owner_postal_code',
        'table': 'PropertyState',
        'displayName': 'Owner Postal Code',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'home_energy_score_id',
        'table': 'PropertyState',
        'displayName': 'Home Energy Score ID',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'generation_date',
        'table': 'PropertyState',
        'displayName': 'PM Generation Date',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
    }, {
        'name': 'release_date',
        'table': 'PropertyState',
        'displayName': 'PM Release Date',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
    }, {
        'name': 'site_eui',
        'table': 'PropertyState',
        'displayName': 'Site EUI',
        'dataType': 'eui',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'site_eui_weather_normalized',
        'table': 'PropertyState',
        'displayName': 'Site EUI Weather Normalized',
        'dataType': 'eui',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'site_eui_modeled',
        'table': 'PropertyState',
        'displayName': 'Site EUI Modeled',
        'dataType': 'eui',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'source_eui',
        'table': 'PropertyState',
        'displayName': 'Source EUI',
        'dataType': 'eui',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'source_eui_weather_normalized',
        'table': 'PropertyState',
        'displayName': 'Source EUI Weather Normalized',
        'dataType': 'eui',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'source_eui_modeled',
        'table': 'PropertyState',
        'displayName': 'Source EUI Modeled',
        'dataType': 'eui',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'energy_alerts',
        'table': 'PropertyState',
        'displayName': 'Energy Alerts',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'space_alerts',
        'table': 'PropertyState',
        'displayName': 'Space Alerts',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'building_certification',
        'table': 'PropertyState',
        'displayName': 'Building Certification',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'analysis_start_time',
        'table': 'PropertyState',
        'displayName': 'Analysis Start Time',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
    }, {
        'name': 'analysis_end_time',
        'table': 'PropertyState',
        'displayName': 'Analysis End Time',
        'dataType': 'datetime',
        'type': 'date',
        'cellFilter': 'date:\'yyyy-MM-dd h:mm a\'',
        'dbField': True,
    }, {
        'name': 'analysis_state',
        'table': 'PropertyState',
        'displayName': 'Analysis State',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'analysis_state_message',
        'table': 'PropertyState',
        'displayName': 'Analysis State Message',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'number_properties',
        'table': 'TaxLotState',
        'displayName': 'Number Properties',
        'dataType': 'integer',
        'type': 'number',
        'dbField': True,
    }, {
        'name': 'block_number',
        'table': 'TaxLotState',
        'displayName': 'Block Number',
        'dataType': 'string',
        'dbField': True,
    }, {
        'name': 'district',
        'table': 'TaxLotState',
        'displayName': 'District',
        'dataType': 'string',
        'dbField': True,
    }
]
