# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-20 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


DROP_ACCOUNT_TABLES = """\
    DROP TABLE IF EXISTS cleansing_rules CASCADE;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20160412_1123'),
        ('data_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.RenameModel('Rules', 'rule'),
        migrations.RenameField(
            model_name='rule',
            old_name='type',
            new_name='data_type',
        ),
        migrations.AddField(
            model_name='rule',
            name='data_quality_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='data_quality.DataQualityCheck'),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.IntegerField(choices=[(0, b'default'), (1, b'custom')], null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='table_name',
            field=models.CharField(blank=True, default=b'PropertyState', max_length=200),
        ),
        migrations.AddField(
            model_name='dataqualitycheck',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunSQL(DROP_ACCOUNT_TABLES),
    ]
