# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0002_auto_20170420_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='category',
        ),
        migrations.AddField(
            model_name='rule',
            name='not_null',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rule',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
